.TH  Tukubai 1 "19 Jan 2023" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
cap(1)
.br

.br
【名前】
.br

.br
cap\ :\ 半角英数の小文字を大文字に変換する
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ cap\ [<f1>\ <f2>\ ..]\ <file>
.br
          cap -d <string>
.br
Version\ :\ Thu\ Jan\ 19\ 03:12:32\ JST\ 2023
.br
Edition\ :\ 1
.br

.br
【説明】
.br

.br
引数で指定したフィールドの半角英小文字を、すべて半角英大文字に変換し
.br
て出力する。変換できない文字（日本語、数字、記号、全角文字）は、変換
.br
されずにそのまま出力される。
.br
<file>として-を指定すると標準入力を使用する。
.br

.br
-dオプションがあると<string>で指定された文字列に対して変換を行なう。
.br

.br
【注意】
.br

.br
	入力ファイル\ <file>\ は省略できない
.br
	フィールド指定\ <f1>\ <f2>\ ...\ を省略すると全フィールド指定となる。
.br
	フィールド指定\ <f1>\ <f2>\ ...\ に0があると全フィールド指定となる。
.br
	\ \ このとき同時に0以外のフィールド指定があってもそれらは無視される。
.br

.br
【例１】
.br

.br
(元データ)
.br

  $ cat data
  001 japan america
  002 england russia

  $ cap 1 2 data
  001 JAPAN america
  002 ENGLAND russia

.br
【例２】
.br

.br

  $ cap -d japan
  JAPAN

.br

.br
last\ modified:\ Sat\ Feb\ \ 4\ 18:01:52\ JST\ 2023
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2023\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
