.TH  Tukubai 1 "19 Oct 2021" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
check_date_name(1)
.br

.br
【名前】
.br

.br
check_date_name\ :\ name\ 形式データの日付をチェックする
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ check_date_name\ <check_file>\ <name_file>
.br
Option\ \ :\ --through\ <string>
.br
Version\ :\ Tue\ Oct\ 19\ 23:46:03\ JST\ 2021
.br
Edition\ :\ 1
.br

.br
【説明】
.br

.br
<check_file>\ に記述されているタグ名、記号(D/W/M)に従って
.br
<name_file>\ の日/週/月の記述が正しいかどうかチェックします。
.br
エラーがあった場合は、コマンドはエラー終了し、標準出力にタグ名と、
.br
記号をを出力します。
.br

.br
<オプション>
.br
--through\ <string>
.br
<check_file>と<name_file>\ のデータが<string>で指定した文字列に
.br
等しい場合は、チェックを実施しません。
.br
<string>のデフォルトは、"_"\ となります。
.br
このオプションは繰り返し使って複数の<string>を指定
.br
できます。
.br

.br
【例１】\ 通常のチェック
.br

.br
[usp1\ usp@\ ~]$\ cat\ check
.br
A\ D.B\ \e
1 .B\ \e
2 .B\ \e
3付
.br
B\ W.B\ \e
1 .B\ \e
2 .B\ \e
3
.br
C\ M.B\ \e
1 .B\ \e
2 .B\ \e
3
.br
D\ _.B\ \e
1 .B\ \e
2 .B\ \e
3ェック無し
.br

.br
[usp1\ usp@\ ~]$\ cat\ data
.br
A\ 20081010
.br
B\ 200852
.br
C_001\ 200813.B\ \e
1 .B\ \e
2 .B\ \e
3として正しく無い
.br
C_002\ _\ \ \ \ \ \ \ \ <--\ _\ データはチェックしない
.br
C_003\ 200804\ \ \ 
.br
D\ 9999
.br
[usp1\ usp@\ ~]$\ check_date_name\ check\ data
.br
C_001\ M
.br

  $ echo $?
  1 

.br
last\ modified:\ Fri\ Aug\ 12\ 12:56:05\ JST\ 2022
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2022\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
