.TH  Tukubai 1 "19 Jan 2023" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
cjoin1(1)
.br

.br
【名前】
.br

.br
cjoin1\ :\ トランザクションファイルにマスタファイルを連結(一致した行のみ連結)
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ cjoin1\ [+ng[<fd>]]\ key=<n>\ <master>\ [<tran>]
.br
Version\ :\ Thu\ Jan\ 19\ 03:12:32\ JST\ 2023
.br
Edition\ :\ 1
.br

.br
【説明】
.br

.br
tranのkey=<n>で指定したキーフィールドがmasterの第1フィールド(キーフィールド)と
.br
一致した行のみtranから抽出して、masterの情報を連結して出力する。連結はtranのキ
.br
ーフィールドの直後にmasterの内容を挿入連結する形で実施される。
.br

.br
masterに-を指定すると標準入力をマスタファイルとする。tranが無指定かまたは-が指
.br
定されている場合には、標準入力がトランザクションファイルとなる。
.br

.br
masterの第1フィールドとtranの第<n>フィールドは整列されていなくてもよく、
.br
キーフィールドに同じ値を持つレコードはいくつあっても構わない。
.br

.br
キーに選択するフィールドは複数指定することもできる。
.br
たとえばkey=3/5のように指定した場合、
.br
tranの第3、第4、第5フィールドを意味するようになる。
.br
またこの場合、masterのキーは第1、第2、第3フィールドとなる。
.br
key=3@5とすると第3、第5フィールドを意味する。
.br
行のフィールド数を意味するNFを使用してNFまたはNF-xの形でフィールド位置を指定す
.br
ることができる。
.br

.br
キー指定にひとつでも0があると全フィールドを指定したことになる。
.br

.br
+ng<fd>オプションを使うことで、一致した行を標準出力ファイルへ、一致しなかった行
.br
をファイルデスクリプタ<fd>のファイルへ出力することが可能。<fd>を省略した場合は
.br
標準エラー出力へ出力する。
.br

.br
tranのキーが整列済みであればcjoin1(1)ではなくjoin1(1)で処理できる。cjoin1(1)は
.br
tranのキーが整列されていないものも処理できるが、masterをすべてメモリに読み込む
.br
ため、メモリ確保エラーが発生する可能性がある。cjoin1(1)はmasterが小さくtranが大
.br
容量な場合に効果的に使用できる。
.br

.br
【例1】基本パターン
.br

.br

  $ cat master
  0000003 杉山______ 26 F
  0000005 崎村______ 50 F
  0000007 梶川______ 42 F

  $

.br

  $ cat tran
  0000005 82 79 16 21 80
  0000001 46 39 8  5  21
  0000004 58 71 20 10 6
  0000009 60 89 33 18 6
  0000003 30 50 71 36 30
  0000007 50 2  33 15 62

  $

.br

  $ cjoin1 key=1 master tran > ok

  $ cat ok
  0000005 崎村______ 50 F 82 79 16 21 80
  0000003 杉山______ 26 F 30 50 71 36 30
  0000007 梶川______ 42 F 50 2  33 15 62

  $

.br
【例2】+ngオプションの使い方
.br

.br

  $ cjoin1 +ng key=1 master tran > ok 2> ng

  $ cat ng
  0000001 46 39 8  5  21
  0000004 58 71 20 10 6
  0000009 60 89 33 18 6

  $

.br
【例3】標準入力の使い方
.br

.br

  $ cat tran | cjoin1 +ng key=1 master > ok 2> ng

  $ cat tran | cjoin1 +ng key=1 master - > ok 2> ng

  $ cat master | cjoin1 +ng key=1 - tran > ok 2> ng

.br
【関連項目】
.br

.br
cjoin0(1)、cjoin1(1)、cjoin2(1)、join0(1)、join2(1)、loopj(1)、loopx(1)、up3(1)
.br
、マスタファイル(5)、トランザクションファイル(5)
.br

.br
last\ modified:\ Sat\ Feb\ \ 4\ 18:01:52\ JST\ 2023
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2023\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
