.TH  Tukubai 1 "21 Apr 2022" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
delf(1)
.br

.br
【名前】
.br

.br
delf\ :\ 指定したフィールドを除いて出力
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ delf\ f1\ f2\ ...\ [file]
.br
        : delf -d f1 f2 ... string
.br
Version\ :\ Thu\ Apr\ 21\ 00:58:47\ JST\ 2022
.br
Edition\ :\ 1
.br

.br
【説明】
.br

.br
fileから、指定したフィールドだけを除いて出力する(delf=delete\ field)。self(1)と
.br
は逆の動作となる。ファイル名指定なし、あるいは、ファイル名が-の時は標準入力を期
.br
待する。
.br

.br
【オプション】
.br

.br
-d\ :\ ダイレクトモード
.br
文字列<string>にdelf\ を適用する。
.br

.br
【例1】
.br

.br

  $ cat data              ←元データ
  0000000 浜地______ 50 F
  0000001 鈴田______ 50 F
  0000003 杉山______ 26 F
  0000004 白土______ 40 M
  0000005 崎村______ 50 F
  0000007 梶川______ 42 F
  0000008 角屋______ 50 F
  0000009 米原______ 68 F
  0000010 柳本______ 50 F
  0000011 安武______ 55 F

  $

.br

  $ delf 2 data           ←第2フィールドを除いて出力する。
  0000000 50 F
  0000001 50 F
  0000003 26 F
  0000004 40 M
  0000005 50 F
  0000007 42 F
  0000008 50 F
  0000009 68 F
  0000010 50 F
  0000011 55 F

  $

.br
【例2】
.br

.br

  $ delf NF data
  0000000 浜地______ 50
  0000001 鈴田______ 50
  0000003 杉山______ 26
  0000004 白土______ 40
  0000005 崎村______ 50
  0000007 梶川______ 42
  0000008 角屋______ 50
  0000009 米原______ 68
  0000010 柳本______ 50
  0000011 安武______ 55

  $

.br
【例3】
.br

.br

  $ delf 2/3 data
  0000000 F
  0000001 F
  0000003 F
  0000004 M
  0000005 F
  0000007 F
  0000008 F
  0000009 F
  0000010 F
  0000011 F

  $

.br
【注意】
.br

.br
入力ファイルが改行文字で終了していない場合、つまり行が尻切れになっている場合は
.br
、ファイル末尾に改行文字が追加されて完結した行になる。
.br

.br
実行時パラメータの最後尾が実際に存在するファイルの名前であればそれを入力ファイルとして開く。
.br
このファイル名は「10」のような数字列であってもかまわない。
.br
最後尾が存在するファイル名でないときはそれをフィールドとして処理し、
.br
入力ファイル名は省略されたものとして標準入力（stdin）を使用する。
.br

.br
【関連項目】
.br

.br
self(1)
.br

.br
last\ modified:\ Fri\ Jul\ 15\ 16:41:13\ JST\ 2022
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2022\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
