.TH  Tukubai 1 "21 Oct 2011" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
extname(1)
.br

.br
【名前】
.br

.br
extname\ :\ パス名からサフィックスを取り出す
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ extname\ <pathname>
.br
Version\ :\ Sun\ Aug\ 19\ 10:16:04\ JST\ 2007
.br
Edition\ :\ 1
.br

.br
【説明】
.br

.br
extname\ コマンドは指定した\ <pathname>\ からサフィックスを出力します。
.br

.br
【例１】
.br

.br

  $ extname /home/usp/hogehoge.c
  c

.br
【参考】
.br

.br
basename\ コマンド\ ＝\ パスを取り除き、ファイル名のみ取り出す
.br
dirname\ コマンド\ ＝\ パスの中からディレクトリ名のみ取り出す
.br
rootname\ コマンド\ ＝\ パスの中からサフィックスを取り除く（USPコマンド）
.br
extname\ コマンド\ ＝\ パスの中からサフィックスを取り出す（USPコマンド）
.br

.br
last\ modified:\ Sat\ Aug\ 13\ 12:25:02\ JST\ 2022
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2022\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
