.TH  Tukubai 1 "21 Feb 2021" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
fsed(1)
.br

.br
【名前】
.br

.br
fsed\ :\ フィールドの文字列の置換
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ fsed\ [-e|-i]\ 's/<org>/<new>/<n>'...\ <file>
.br
Version\ :\ Sun\ Feb\ 21\ 04:35:05\ JST\ 2021
.br
Edition\ :\ 1
.br

.br
【説明】
.br

.br
ファイル\ <file>\ のフィールド\ <n>\ の中で、文字列\ <org>\ を文字列\ <new>
.br
に置換します。<n>\ に\ 'g'\ を指定すると、全フィールドの指定になります。
.br

.br
-e\ オプションを使うと\ <org>\ を正規表現と解釈します。-i\ オプションを
.br
使うと大文字／小文字を区別しない正規表現になります。
.br

.br
置換指定は複数指定できます。この場合、-e/-i\ オプションは、正規表現を
.br
使う置換指定毎に指定する必要があります。
.br

.br

.br
【例１】
.br

.br
第１フィールドの\ tokyo\ を\ TOKYO\ に、第３フィールドの\ osaka\ をOSAKA
.br
に置換します。
.br

.br

  $ cat data1
  tokyo 1234 tokyo 5678
  osaka 1234 osaka 5678

.br

  $ fsed 's/tokyo/TOKYO/1' 's/osaka/OSAKA/3' data1
  TOKYO 1234 tokyo 5678
  osaka 1234 OSAKA 5678

.br
【例２】
.br

.br
全フィールドの\ tokyo\ を\ yokohama\ に置換します。
.br

  $ fsed 's/tokyo/yokohama/g' data1
  yokohama 1234 yokohama 5678
  osaka 1234 osaka 5678

.br
【例３】
.br

.br
正規表現を使います。
.br

  $ cat data3
  Tokyo 1234
  tokyo 5678
  TOKYO 7777

.br

  $ fsed -e 's/^[Tt]okyo$/東京/1' data3
  東京 1234
  東京 5678
  TOKYO 7777

.br
【例４】
.br

.br
大文字／小文字を区別しない正規表現を使います。
.br

  $ fsed -i 's/^tokyo$/東京/1' data3
  東京 1234
  東京 5678
  東京 7777

.br
【例５】
.br

.br
複数の置換指定を使います。
.br

  $ fsed 's/tokyo/横浜/1' -i 's/tokyo/川崎/1' data3
  川崎 1234
  横浜 5678
  川崎 7777

.br
【例６】
.br

.br
置換指定の区切り文字\ '/'\ を置換対象にする場合。
.br

  $ cat data6
  001 /home/MANUAL/TOOL/fsed.txt

.br
data6\ の中で、'/'\ を\ '-'\ に置換する場合、置換指定の区切り文字を\ '/'
.br
以外の文字（本例では\ ','）にします。この文字には、任意の\ ASCII\ 文字
.br
を指定できます。
.br

.br

  $ fsed 's,/,-,2' data6
  001 -home-MANUAL-TOOL-fsed.txt

.br
区切り文字は\ '/'\ のままにしておいて、パターン中の\ '/'\ に\ '.B\ \e
'\ を前置
.br
してもよいです。
.br

.br

  $ fsed 's/\//-/2' data6
  001 -home-MANUAL-TOOL-fsed.txt

.br
last\ modified:\ Fri\ Jul\ 15\ 15:42:38\ JST\ 2022
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2022\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
