.TH  Tukubai 1 "" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
ido(1)
.br

.br
【名前】\ 
.br
ido\ \ :\ テキストの位置を移動する。
.br

.br
【書式】
.br
Usage\ \ \ :\ ido\ <y>\ <x>\ <file>
.br
          ido -f[<string>] <y> <x> <file>
.br
Version\ :\ Mon\ Mar\ 18\ 07:54:16\ JST\ 2013
.br
Edition\ :\ 1
.br

.br
【説明】
.br
テキストファイル全体を指定した位置に移動して出力します。
.br
引数は、移動するテキストの開始位置を、"y"は下に移動する行数、"x"は右に移動する
.br
文字数(半角文字間隔)を指定します。
.br
主に"overlay"と組み合わせて成形済みの複数のテキストファイルを重ねあわせて帳票
.br
などを作成するのに使用します。
.br

.br
【例１】
.br
(元データ)
.br

  $ cat data1
  ★教科別得点
  No  氏\1 \2 \3B  C  D  E
  =======================
  000 浜地 91 59 20 76 54
  001 鈴田 46 39  8  5 21
  003 杉山 30 50 71 36 30
  004 白土 58 71 20 10  6
  005 崎村 82 79 16 21 80
  007 梶川 50  2 33 15 62

.br
"data1"を右横方向に半角20文字分だけ移動します。
.br

  $ ido 0 20 data1
                    ★教科別得点
.br
                    No  氏名  A  B  C  D  E
.br
                    =======================
.br
                    000 浜地 91 59 20 76 54
.br
                    001 鈴田 46 39  8  5 21
.br
                    003 杉山 30 50 71 36 30
.br
                    004 白土 58 71 20 10  6
.br
                    005 崎村 82 79 16 21 80
.br
                    007 梶川 50  2 33 15 62
.br
  → 20文字分右横へ移動

.br
"data1"を右横方向に半角8文字分、下方向に3行分移動します。
.br

  $ ido 3 8 data1
                                  --------------
.br
                                  ↓
.br
                                  ↓   3行分下へ移動
.br
                                  ↓
.br
        ★教科別得点
.br
        No  氏名  A  B  C  D  E
.br
        =======================
.br
        000 浜地 91 59 20 76 54
.br
        001 鈴田 46 39  8  5 21
.br
        003 杉山 30 50 71 36 30
.br
        004 白土 58 71 20 10  6
.br
        005 崎村 82 79 16 21 80
.br
        007 梶川 50  2 33 15 62
.br
  →→→→ ８文字分右横へ移動

.br
【例３】
.br
フィールド移動
.br
-f\ オプションをつけることによってフィールドを移動し、
.br
移動した分のフィールドは、デフォルト\ "@"\ でパディングします。
.br

  $ cat data
  1 2 3
  4 5 6

  $ ido -f 1 2 data
  @ @ @ @ @ 
  @ @ 1 2 3
  @ @ 4 5 6

  $ ido -f0 1 2 data
  0 0 0 0 0 
  0 0 1 2 3
  0 0 4 5 6

.br
last\ modified:\ Fri\ Jul\ 15\ 15:42:38\ JST\ 2022
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2022\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
