.TH  Tukubai 1 "" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
man2(1)
.br

.br
【名前】
.br

.br
man2\ :\ USP\ コマンドのマニュアル表示
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ man2\ <command>
.br
Version\ :\ Jul\ 28\ 14:44:40\ JST\ 2022
.br

.br
【説明】
.br

.br
USP\ コマンドのマニュアルを表示します。
.br

.br
【例】
.br

.br

  $ man2 join0   <-- join0 のマニュアルを表示します。

.br
last\ modified:\ Mon\ Aug\ \ 8\ 12:16:16\ JST\ 2022
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2022\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
