.TH  Tukubai 1 "28 Aug 2022" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
msort(1)
.br

.br
【名前】
.br

.br
msort\ :\ オンメモリソート
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ msort\ key=<key>\ [<file>]
.br
Version\ :\ Tue\ Mar\ 21\ 06:05:17\ JST\ 2023
.br
Edition\ :\ 1
.br

.br
【説明】
.br

.br
key=<key>\ にしたがって\ <file>\ のソートを行います。<key>\ として、フィ
.br
ールドの位置を指定できます。
.br

.br
\ \ msort\ key=2\ file
.br
\ \ msort\ key=2/5\ file
.br
\ \ msort\ key=3@1@NF\ file
.br

.br
キーの長さやキーフィールド数の制限はありません。日本語などのマルチバ
.br
イト文字が含まれていても構いません。フィールド位置の後に\ r\ を付ける
.br
と、そのフィールドは降順にソートされます。n\ を付けると数値として比較
.br
されます。nr\ を付けると、数値として比較されて降順にソートされます。
.br
/\ の前後のフィールドにソート種別を付ける場合は、前後で揃っている必要
.br
があります。
.br

.br
\ \ msort\ key=2n/5n\ \ file\ \ \ \ \ \ ○
.br
\ \ msort\ key=2n/5nr\ file\ \ \ \ \ \ ×
.br
\ \ msort\ key=2n/5r\ \ file\ \ \ \ \ \ ×
.br

.br
ファイル名を指定しない、或は\ -\ を指定した場合、標準入力から読み込み
.br
ます。
.br

.br
last\ modified:\ Tue\ Mar\ 21\ 06:08:57\ JST\ 2023
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2023\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
