.TH  Tukubai 1 "02 Jan 2026" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
ratio(1)
.br

.br
【名前】
.br

.br
ratio\ :\ 構成比算出
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ ratio\ key=<key>\ [<file>]
.br
Option\ \ :\ ref=<ref>\ \ \ \ \ \ \ \ \ \ \ \ \ ←参照キーの指定
.br
        : -<s>                  ←小数点以下の精度
.br
        : +<n>h                 ←先頭<n>行をヘッダーとみなす
.br
Version\ :\ Fri\ Jan\ 02\ 05:04:02\ JST\ 2026
.br

.br
【説明】
.br

.br
引数のファイルまたは標準入力のテキストデータに対し、key=で指定したフィールドに
.br
対して全行の合計に対する各フィールドの値の構成比を算出し、次のフィールドに挿入
.br
して出力する。
.br
<file>として-を指定するか省略すると標準入力を使用する。
.br

.br
【例1】
.br

.br

  $ cat data
  a店 1日目 103  62               ←店名 日付 売数 客数
  b店 1日目 210 113
  c店 1日目 81   52
  d店 1日目 75   48
  e店 1日目 211 140

  $

.br
売数(第3フィールド)の店別構成比を求めて売数の次のフィールドに挿入するには、次の
.br
ようにコマンドを実行する。
.br

.br

  $ ratio key=3 data |  keta
  a店 1日目 103 15.1  62          ←第4フィールドが構成比になっている
  b店 1日目 210 30.9 113
  c店 1日目  81 11.9  52
  d店 1日目  75 11.0  48
  e店 1日目 211 31.0 140

  $

.br
【例2】refオプション
.br

.br
ref=で指定したフィールドをキーフィールドとし、キーフィールドの値が同じ行の中で
.br
構成比を計算して出力する。なお、キーフィールドはあらかじめ整列されていることが
.br
条件となる。
.br

.br

  $ cat data
  a店 1日目 103  62               ←店名 日付 売数 客数
  a店 2日目 157  94
  a店 3日目   62  30
  b店 1日目 210 113
  b店 2日目 237 121
  b店 3日目 150  82
  c店 1日目   81  52
  c店 2日目   76  49
  c店 3日目   38  21
  d店 1日目   75  48
  d店 2日目   72  42
  d店 3日目   34  19
  e店 1日目 211 140
  e店 2日目 149  91
  e店 3日目 120  73

  $

.br
各日(第2フィールド)毎に店別の売数(第3フィールド)の構成比を求める。
.br

.br

  $ sort -k2,2 -k1,1 data | ratio ref=2 key=3 | keta
  a店 1日目 103 15.1  62          ←第4フィールドが1日目における構成比
  b店 1日目 210 30.9 113
  c店 1日目  81 11.9  52
  d店 1日目  75 11.0  48
  e店 1日目 211 31.0 140
  a店 2日目 157 22.7  94          ←第4フィールドが2日目における構成比
  b店 2日目 237 34.3 121
  c店 2日目  76 11.0  49
  d店 2日目  72 10.4  42
  e店 2日目 149 21.6  91
  a店 3日目  62 15.3  30          ←第4フィールドが3日目における構成比
  b店 3日目 150 37.1  82
  c店 3日目   38  9.4  21
  d店 3日目   34  8.4  19
  e店 3日目 120 29.7  73

  $

.br
【例3】+hオプション
.br

.br
+<n>hオプションを付けると、先頭の<n>行を飛ばして構成比を計算する。先頭行に既に
.br
項目名などのヘッダーが付与されているデータを計算する場合などに使用する。新たに
.br
増える構成比のフィールドのヘッダーは@となる。
.br

.br

  $ cat data
  店   日付 売数 客数             ←項目名のヘッダー
  a店 1日目   103  62
  b店 1日目   210  113
  c店 1日目    81  52
  d店 1日目    75  48
  e店 1日目   211  140

  $

.br
先頭行を飛ばして売数(第3フィールド)の店別構成比を求めて売数の次のフィールドに挿
.br
入する。
.br

.br

  $ ratio +h key=3 data |  keta
  店   日付 売数     @ 客数                ←先頭行はそのまま(計算しない)
  a店 1日目  103 15.1    62 ←第4フィールドが構成比になっている
  b店 1日目  210 30.9  113
  c店 1日目   81 11.9   52
  d店 1日目   75 11.0   48
  e店 1日目  211 31.0  140

  $

.br
【例4】-<s>オプション
.br

.br
-<数値>で構成比の小数点以下の精度を指定できる。
.br

.br

  $ cat data
  a店 1日目 103  62               ←店名 日付 売数 客数
  b店 1日目 210 113
  c店 1日目 81   52
  d店 1日目 75   48
  e店 1日目 211 140

  $

.br
売数(第3フィールド)の店別構成比を小数点3桁まで求める。
.br

.br

  $ ratio -3 key=3 data |  keta
  a店 1日目 103 15.147  62
  b店 1日目 210 30.882 113
  c店 1日目  81 11.912  52
  d店 1日目  75 11.029  48
  e店 1日目 211 31.029 140

  $

.br
【関連項目】
.br

.br
kasan(1)、plus(1)、sm2(1)、sm4(1)、sm5(1)、ysum(1)
.br

.br
last\ modified:\ Fri\ Jan\ 02\ 05:13:54\ JST\ 2026
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2026\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
