.TH  Tukubai 1 "" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
タグ形式(5)
.br

.br
【名前】
.br

.br
タグ形式\ :\ 1行目にヘッダがついたフィールド形式
.br

.br
【書式】
.br

.br
ヘッダ1\ ヘッダ2\ ヘッダ3...
.br
フィールド1\ フィールド2\ フィールド3...
.br
...
.br

.br
【説明】
.br

.br
タグ形式(5)はフィールド形式(5)のデータの先頭行にヘッダが配置されたもの。主に次
.br
の用途で使用される。
.br

.br
-\ 複数のネームファイル(5)を単一のファイルにまとめる
.br
-\ フィールド数がきわめて多い場合
.br

.br
ネームファイル(5)を使用することでフィールドに名前を与えることはできるが、1つの
.br
鍵にいくつもの値が存在するケースではファイル数が増えることになり扱いにくい面が
.br
ある。タグ形式(5)はこうした場合に単一ファイル化する方法として利用できる。タグ
.br
形式(5)はこうした場合に単一ファイル化する方法として利用できる。
.br

.br

.br
【例1】
.br

.br
ID\ DATE\ AGE\ GENDER\ VALUE
.br
0001\ 20111008\ 23\ F\ 0.845814
.br
0002\ 20111009\ 15\ M\ 0.193475
.br
0003\ 20111010\ 81\ F\ 0.484983
.br
0004\ 20111011\ 15\ F\ 0.491736
.br
0005\ 20111012\ 91\ F\ 0.893188
.br
0006\ 20111013\ 22\ M\ 0.571077
.br
0007\ 20111014\ 33\ F\ 0.502931
.br
0008\ 20111015\ 56\ M\ 0.0401409
.br
0009\ 20111016\ 10\ M\ 0.013111
.br
0010\ 20111017\ 72\ F\ 0.482945
.br

.br
【関連項目】
.br

.br
フィールド形式(5)、ネーム形式(5)、ネームファイル(5)
.br

.br
last\ modified:\ Fri\ Aug\ \ 5\ 07:43:22\ JST\ 2022
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2022\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br

.br
