.TH  Tukubai 1 "" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
トランザクションファイル(5)
.br

.br
【名前】
.br

.br
トランザクションファイル\ :\ トランザクションの性質を満たすフィールド形式(5)のフ
.br
ァイル
.br

.br
【書式】
.br

.br
第1フィールド\ 第2フィールド\ 第3フィールド\ ...
.br
...
.br

.br
【説明】
.br

.br
売上データなど随時データの追加などが実施されるタイプのデータはトランザクション
.br
と呼ばれている。トランザクションは短縮してトランと呼ばれることも多い。
.br

.br
ユニケージ開発手法では、トランザクションに該当するフィールド形式(5)のファイルを
.br
トランザクションファイル(5)と呼んでいる。
.br

.br
トランザクションファイル(5)は短縮してトランと呼ばれることがあり、また、Tukubai
.br
コマンドマニュアルではtranと表記される。トランザクションファイル(5)とは対照的に
.br
データ変更のタイミングがあらかじめ定めされており、キーフィールドが重複せずかつ
.br
整列されているようなフィールド形式(5)のファイルはマスタファイル(5)と呼ばれてい
.br
る。
.br

.br
【例1】
.br

.br
トランザクションファイル(5)の例は次のとおり。
.br

.br
\ \ \ 20110405\ 001\ 13513543
.br
\ \ \ 20110405\ 002\ 3403346
.br
\ \ \ 20110406\ 001\ 3543024
.br
\ \ \ 20110406\ 002\ 12412311
.br
\ \ \ 20110406\ 003\ 88797982
.br
\ \ \ 20110407\ 001\ 1354131
.br
\ \ \ 20110407\ 002\ 12343423
.br
\ \ \ 20110407\ 003\ 7657765
.br

.br
【関連項目】
.br

.br
マスタファイル(5)、ネームファイル(5)、フィールド形式(5)、タグ形式(5)、ネーム形
.br
式(5)
.br

.br
last\ modified:\ Thu\ Aug\ 11\ 10:08:20\ JST\ 2022
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2022\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
