.TH  Tukubai 1 "" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
uconv(1)
.br

.br
【名前】
.br

.br
uconv\ :\ UTF-8\ <=>\ Shift\ JIS\ /\ EUC-JP\ コード変換
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ uconv\ <field>\ <str>\ <file>
.br
Option\ \ :\ --through\ <str>
.br
Version\ :\ Sun\ Aug\ 28\ 13:24:22\ JST\ 2022
.br
Edition\ :\ 1
.br

.br
【説明】
.br

.br
UTF-8\ と\ Shif-JIS,\ EUC-JP\ の相互の文字コード変換を行います。オプショ
.br
ンと変換の対応は、以下のようになります。
.br

.br
-stou.B\ \e
1 .B\ \e
2 .B\ \e
3ら\ UTF-8
.br
-utos.B\ \e
1 .B\ \e
2 .B\ \e
3ら\ Shift-JIS
.br
-stou.B\ \e
1 .B\ \e
2 .B\ \e
3ら\ UTF-8
.br
-utos.B\ \e
1 .B\ \e
2 .B\ \e
3ら\ EUC-JP
.br
-ltou.B\ \e
1 .B\ \e
2 .B\ \e
3ら\ UTF-8
.br
-utol.B\ \e
1 .B\ \e
2 .B\ \e
3ら\ ISO-8851-1
.br

.br
ファイル名が省略された時及び\ "-"\ の時は標準入力から入力します。
.br

.br
last\ modified:\ Sun\ Aug\ 28\ 13:25:04\ JST\ 2022
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2022\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
