.TH  Tukubai 1 "" "usp Tukubai" "Tukubai コマンド マニュアル"

.br
uriencode
.br

.br
【名前】
.br

.br
uriencode\ :\ URI\ エンコードを行なう
.br

.br
【書式】
.br

.br
Usage\ \ \ :\ uriencode\ [<file>]
.br
          uriencode <field> ... [<file>]
.br
          uriencode num=<n> [<file>]
.br
          uriencode -a [<file>]
.br
Version\ :\ Tue\ Mar\ 21\ 09:07:51\ JST\ 2023
.br

.br
【説明】
.br

.br
標準入力を読み込み、引数で指定されたポリシーにしたがって、入力データ
.br
を\ RFC\ 3986\ で定義された\ URI\ エンコードを行います。エンコード方式は
.br
パーセントエンコードです。エンコード対象の文字は非予約文字以外です。
.br
RFC\ 3986\ では、ASCIIのコード範囲内の英字（大文字・小文字）、数字、ハ
.br
イフン\ '-'、ピリオド\ '.'、アンダースコア\ '_'、チルダ\ '~'\ を非予約文
.br
字としています。
.br

.br
後述する全体エンコードモード以外の動作モードでは、'\\'\ をエスケープ文
.br
字と解釈します。'\\\\'\ は\ '\\'、'\\n'\ は改行文字と解釈されます。他の文字
.br
が続く\ '\\'\ は無視されます。
.br

.br
<file>\ を指定しないか\ "-"\ を指定した場合は標準入力を読み込みます。
.br

.br
【例１】\ (行単位エンコード\ :\ <file>\ のみを指定した場合)
.br
<file>\ のみを指定した場合は、一行毎にエンコードします。改行文字はエ
.br
ンコードされず、そのまま出力されます。'\\'\ はエスケープ文字と解釈され
.br
ます。
.br

  $ cat data
  a b c d e
  あ い\\ う\n え お
  か き く け こ

.br

  $ uriencode data
  a%20b%20c%20d%20e
  %E3%81%82%20%E3%81%84%5C%20%E3%81%86%0A%20%E3%81%88%20%E3%81%8A
  %E3%81%8B%20%E3%81%8D%20%E3%81%8F%20%E3%81%91%20%E3%81%93

.br
【例２】\ (フィールドエンコード\ :\ フィールドを指定した場合)
.br
フィールドを指定した場合は、指定されたフィールドのみをエンコードしま
.br
す。フィールド指定には\ NF\ や\ NF-1\ なども使えます。連続したフィールド
.br
を指定する場合は\ 3/5\ のように指定することができます。フィールドは昇
.br
順に指定します。空白と改行文字はエンコードされず、そのまま出力されま
.br
す。'\\'\ はエスケープ文字と解釈されます。
.br

  $ uriencode 1 3 5 data
  a b c d e
  %E3%81%82 い\\ %E3%81%86%0A え %E3%81%8A
  %E3%81%8B き %E3%81%8F け %E3%81%93

.br
【例３】\ (先頭スキップエンコード\ :\ num\ オプションを指定した場合)
.br
num\ オプションを指定した場合は、行頭の\ <n>\ フィールドをそのまま出力
.br
し、それ以降から行末までをエンコードします。エンコード対象部分の
.br

.br
白は連続していてもそのままエンコードされます。改行文字はエンコードさ
.br
れず、そのまま出力されます。'\\'\ はエスケープ文字と解釈されます。
.br

  $ uriencode num=2 data
  a b c%20d%20e
  あ い\\ %E3%81%86%0A%20%E3%81%88%20%E3%81%8A
  か き %E3%81%8F%20%E3%81%91%20%E3%81%93

.br
【例４】\ (全体エンコード\ :\ -a\ オプションを指定した場合)
.br
-a\ オプションを指定した場合は、ファイル全体をエンコードします。空白
.br
や改行文字もエンコードされます。'\\'\ はエスケープ文字と解釈されず、そ
.br
のままエンコードされて出力されます。
.br

  $ uriencode -a < data
  a%20b%20c%20d%20e%0A%E3%81%82%20%E3%81%84%5C%5C%20%E3%81%86%5Cn%20
  %E3%81%88%20%E3%81%8A%0A%E3%81%8B%20%E3%81%8D%20%E3%81%8F%20%E3%81
  %91%20%E3%81%93%0A

.br
このモードでは出力の末尾に改行文字はありません。
.br

.br
last\ modified:\ Tue\ Mar\ 21\ 09:15:00\ JST\ 2023
.br
Contact\ us:\ uecinfo@usp-lab.com
.br
Copyright\ (c)\ 2012-2023\ Universal\ Shell\ Programming\ Laboratory\ All\ Rights
.br
