#!/usr/local/bin/bash -xv

tmp=/tmp/$$
+ tmp=/tmp/10535

dir=$(dirname $0)
dirname $0)
dirname $0
++ dirname ./regress.all
+ dir=.
cd $dir
+ cd .

cat << FIN > $tmp-ver
python2.7
python2.6
python2.5
python2.4
FIN
+ cat

cat $tmp-ver	|
while read com ; do
	./yarr.test $com
	./nameread.test $com
done
+ read com
+ cat /tmp/10535-ver
+ ./yarr.test python2.7
#!/usr/local/bin/bash -xv
#
# test script of yarr 
#
# usage: ./yarr.test <python ver>

tmp=/tmp/$$
+ tmp=/tmp/10540

dir=$(dirname $0)/..
dirname $0)/..
dirname $0
++ dirname ./yarr.test
+ dir=./..
cd $dir
+ cd ./..

scr=./COMMANDS/yarr
+ scr=./COMMANDS/yarr
com="$1 ${scr}"
+ com='python2.7 ./COMMANDS/yarr'
[ "$1" = "" ] && com=./COMMANDS/yarr
+ '[' python2.7 = '' ']'

ERROR_CHECK(){
	[ "$(echo ${PIPESTATUS[@]} | tr -d ' 0')" = "" ] && return

	echo $1
	rm -f $tmp-*
	exit 1
}

###########################################
#TEST1: no option use

cat << FIN > $tmp-in
山田
山本
田中
FIN
+ cat

cat << FIN > $tmp-out
山田 山本 田中
FIN
+ cat

${com} $tmp-in > $tmp-ans
+ python2.7 ./COMMANDS/yarr /tmp/10540-in
diff $tmp-ans $tmp-out
+ diff /tmp/10540-ans /tmp/10540-out
[ $? -eq 0 ] ; ERROR_CHECK "TEST1 error"
+ '[' 0 -eq 0 ']'
+ ERROR_CHECK 'TEST1 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

rm -f $tmp-*
+ rm -f /tmp/10540-ans /tmp/10540-in /tmp/10540-out
echo "${com}" OK
+ echo 'python2.7 ./COMMANDS/yarr' OK
exit 0
+ exit 0
+ ./nameread.test python2.7
#!/usr/local/bin/bash -xv
#
# test script of nameread
#
# usage: ./YARR.bash <python ver>

dir=$(dirname $0)/..
dirname $0)/..
dirname $0
++ dirname ./nameread.test
+ dir=./..
cd $dir
+ cd ./..

scr=./COMMANDS/nameread
+ scr=./COMMANDS/nameread
com="$1 ${scr}"
+ com='python2.7 ./COMMANDS/nameread'
[ "$1" = "" ] && com=./COMMANDS/nameread
+ '[' python2.7 = '' ']'

ERROR_CHECK(){
	[ "$(echo ${PIPESTATUS[@]} | tr -d ' 0')" = "" ] && return

	echo $1
	rm -f $tmp-*
	exit 1
}

tmp=/tmp/$$
+ tmp=/tmp/10550

cat << FIN > $tmp-name
A01 1
A02 2
A03 3
A10 5
FIN
+ cat

###########################################
#TEST1: ordinaly use

ANS=$( ${com} A01 $tmp-name )
 ${com} A01 $tmp-name )
 ${com} A01 $tmp-name 
++ python2.7 ./COMMANDS/nameread A01 /tmp/10550-name
+ ANS=1
[ "${ANS}" = "1" ] ; ERROR_CHECK "Test1 error"
+ '[' 1 = 1 ']'
+ ERROR_CHECK 'Test1 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

###########################################
#TEST2: regular expression

${com} -e '^A0[0-9]$' $tmp-name > $tmp-out
+ python2.7 ./COMMANDS/nameread -e '^A0[0-9]$' /tmp/10550-name

cat << FIN > $tmp-ans
1
2
3
FIN
+ cat

diff $tmp-ans $tmp-out ; ERROR_CHECK "Test2 error"
+ diff /tmp/10550-ans /tmp/10550-out
+ ERROR_CHECK 'Test2 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

###########################################
#TEST2: regular expression with output of names

${com} -el '^A0[0-9]$' $tmp-name > $tmp-out
+ python2.7 ./COMMANDS/nameread -el '^A0[0-9]$' /tmp/10550-name

cat << FIN > $tmp-ans
A01 1
A02 2
A03 3
FIN
+ cat

diff $tmp-ans $tmp-out ; ERROR_CHECK "Test3 error"
+ diff /tmp/10550-ans /tmp/10550-out
+ ERROR_CHECK 'Test3 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

rm $tmp-*
+ rm /tmp/10550-ans /tmp/10550-name /tmp/10550-out
echo "${com}" OK
+ echo 'python2.7 ./COMMANDS/nameread' OK
exit 0
+ exit 0
+ read com
+ ./yarr.test python2.6
#!/usr/local/bin/bash -xv
#
# test script of yarr 
#
# usage: ./yarr.test <python ver>

tmp=/tmp/$$
+ tmp=/tmp/10570

dir=$(dirname $0)/..
dirname $0)/..
dirname $0
++ dirname ./yarr.test
+ dir=./..
cd $dir
+ cd ./..

scr=./COMMANDS/yarr
+ scr=./COMMANDS/yarr
com="$1 ${scr}"
+ com='python2.6 ./COMMANDS/yarr'
[ "$1" = "" ] && com=./COMMANDS/yarr
+ '[' python2.6 = '' ']'

ERROR_CHECK(){
	[ "$(echo ${PIPESTATUS[@]} | tr -d ' 0')" = "" ] && return

	echo $1
	rm -f $tmp-*
	exit 1
}

###########################################
#TEST1: no option use

cat << FIN > $tmp-in
山田
山本
田中
FIN
+ cat

cat << FIN > $tmp-out
山田 山本 田中
FIN
+ cat

${com} $tmp-in > $tmp-ans
+ python2.6 ./COMMANDS/yarr /tmp/10570-in
diff $tmp-ans $tmp-out
+ diff /tmp/10570-ans /tmp/10570-out
[ $? -eq 0 ] ; ERROR_CHECK "TEST1 error"
+ '[' 0 -eq 0 ']'
+ ERROR_CHECK 'TEST1 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

rm -f $tmp-*
+ rm -f /tmp/10570-ans /tmp/10570-in /tmp/10570-out
echo "${com}" OK
+ echo 'python2.6 ./COMMANDS/yarr' OK
exit 0
+ exit 0
+ ./nameread.test python2.6
#!/usr/local/bin/bash -xv
#
# test script of nameread
#
# usage: ./YARR.bash <python ver>

dir=$(dirname $0)/..
dirname $0)/..
dirname $0
++ dirname ./nameread.test
+ dir=./..
cd $dir
+ cd ./..

scr=./COMMANDS/nameread
+ scr=./COMMANDS/nameread
com="$1 ${scr}"
+ com='python2.6 ./COMMANDS/nameread'
[ "$1" = "" ] && com=./COMMANDS/nameread
+ '[' python2.6 = '' ']'

ERROR_CHECK(){
	[ "$(echo ${PIPESTATUS[@]} | tr -d ' 0')" = "" ] && return

	echo $1
	rm -f $tmp-*
	exit 1
}

tmp=/tmp/$$
+ tmp=/tmp/10580

cat << FIN > $tmp-name
A01 1
A02 2
A03 3
A10 5
FIN
+ cat

###########################################
#TEST1: ordinaly use

ANS=$( ${com} A01 $tmp-name )
 ${com} A01 $tmp-name )
 ${com} A01 $tmp-name 
++ python2.6 ./COMMANDS/nameread A01 /tmp/10580-name
+ ANS=1
[ "${ANS}" = "1" ] ; ERROR_CHECK "Test1 error"
+ '[' 1 = 1 ']'
+ ERROR_CHECK 'Test1 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

###########################################
#TEST2: regular expression

${com} -e '^A0[0-9]$' $tmp-name > $tmp-out
+ python2.6 ./COMMANDS/nameread -e '^A0[0-9]$' /tmp/10580-name

cat << FIN > $tmp-ans
1
2
3
FIN
+ cat

diff $tmp-ans $tmp-out ; ERROR_CHECK "Test2 error"
+ diff /tmp/10580-ans /tmp/10580-out
+ ERROR_CHECK 'Test2 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

###########################################
#TEST2: regular expression with output of names

${com} -el '^A0[0-9]$' $tmp-name > $tmp-out
+ python2.6 ./COMMANDS/nameread -el '^A0[0-9]$' /tmp/10580-name

cat << FIN > $tmp-ans
A01 1
A02 2
A03 3
FIN
+ cat

diff $tmp-ans $tmp-out ; ERROR_CHECK "Test3 error"
+ diff /tmp/10580-ans /tmp/10580-out
+ ERROR_CHECK 'Test3 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

rm $tmp-*
+ rm /tmp/10580-ans /tmp/10580-name /tmp/10580-out
echo "${com}" OK
+ echo 'python2.6 ./COMMANDS/nameread' OK
exit 0
+ exit 0
+ read com
+ ./yarr.test python2.5
#!/usr/local/bin/bash -xv
#
# test script of yarr 
#
# usage: ./yarr.test <python ver>

tmp=/tmp/$$
+ tmp=/tmp/10600

dir=$(dirname $0)/..
dirname $0)/..
dirname $0
++ dirname ./yarr.test
+ dir=./..
cd $dir
+ cd ./..

scr=./COMMANDS/yarr
+ scr=./COMMANDS/yarr
com="$1 ${scr}"
+ com='python2.5 ./COMMANDS/yarr'
[ "$1" = "" ] && com=./COMMANDS/yarr
+ '[' python2.5 = '' ']'

ERROR_CHECK(){
	[ "$(echo ${PIPESTATUS[@]} | tr -d ' 0')" = "" ] && return

	echo $1
	rm -f $tmp-*
	exit 1
}

###########################################
#TEST1: no option use

cat << FIN > $tmp-in
山田
山本
田中
FIN
+ cat

cat << FIN > $tmp-out
山田 山本 田中
FIN
+ cat

${com} $tmp-in > $tmp-ans
+ python2.5 ./COMMANDS/yarr /tmp/10600-in
diff $tmp-ans $tmp-out
+ diff /tmp/10600-ans /tmp/10600-out
[ $? -eq 0 ] ; ERROR_CHECK "TEST1 error"
+ '[' 0 -eq 0 ']'
+ ERROR_CHECK 'TEST1 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

rm -f $tmp-*
+ rm -f /tmp/10600-ans /tmp/10600-in /tmp/10600-out
echo "${com}" OK
+ echo 'python2.5 ./COMMANDS/yarr' OK
exit 0
+ exit 0
+ ./nameread.test python2.5
#!/usr/local/bin/bash -xv
#
# test script of nameread
#
# usage: ./YARR.bash <python ver>

dir=$(dirname $0)/..
dirname $0)/..
dirname $0
++ dirname ./nameread.test
+ dir=./..
cd $dir
+ cd ./..

scr=./COMMANDS/nameread
+ scr=./COMMANDS/nameread
com="$1 ${scr}"
+ com='python2.5 ./COMMANDS/nameread'
[ "$1" = "" ] && com=./COMMANDS/nameread
+ '[' python2.5 = '' ']'

ERROR_CHECK(){
	[ "$(echo ${PIPESTATUS[@]} | tr -d ' 0')" = "" ] && return

	echo $1
	rm -f $tmp-*
	exit 1
}

tmp=/tmp/$$
+ tmp=/tmp/10610

cat << FIN > $tmp-name
A01 1
A02 2
A03 3
A10 5
FIN
+ cat

###########################################
#TEST1: ordinaly use

ANS=$( ${com} A01 $tmp-name )
 ${com} A01 $tmp-name )
 ${com} A01 $tmp-name 
++ python2.5 ./COMMANDS/nameread A01 /tmp/10610-name
+ ANS=1
[ "${ANS}" = "1" ] ; ERROR_CHECK "Test1 error"
+ '[' 1 = 1 ']'
+ ERROR_CHECK 'Test1 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

###########################################
#TEST2: regular expression

${com} -e '^A0[0-9]$' $tmp-name > $tmp-out
+ python2.5 ./COMMANDS/nameread -e '^A0[0-9]$' /tmp/10610-name

cat << FIN > $tmp-ans
1
2
3
FIN
+ cat

diff $tmp-ans $tmp-out ; ERROR_CHECK "Test2 error"
+ diff /tmp/10610-ans /tmp/10610-out
+ ERROR_CHECK 'Test2 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

###########################################
#TEST2: regular expression with output of names

${com} -el '^A0[0-9]$' $tmp-name > $tmp-out
+ python2.5 ./COMMANDS/nameread -el '^A0[0-9]$' /tmp/10610-name

cat << FIN > $tmp-ans
A01 1
A02 2
A03 3
FIN
+ cat

diff $tmp-ans $tmp-out ; ERROR_CHECK "Test3 error"
+ diff /tmp/10610-ans /tmp/10610-out
+ ERROR_CHECK 'Test3 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

rm $tmp-*
+ rm /tmp/10610-ans /tmp/10610-name /tmp/10610-out
echo "${com}" OK
+ echo 'python2.5 ./COMMANDS/nameread' OK
exit 0
+ exit 0
+ read com
+ ./yarr.test python2.4
#!/usr/local/bin/bash -xv
#
# test script of yarr 
#
# usage: ./yarr.test <python ver>

tmp=/tmp/$$
+ tmp=/tmp/10630

dir=$(dirname $0)/..
dirname $0)/..
dirname $0
++ dirname ./yarr.test
+ dir=./..
cd $dir
+ cd ./..

scr=./COMMANDS/yarr
+ scr=./COMMANDS/yarr
com="$1 ${scr}"
+ com='python2.4 ./COMMANDS/yarr'
[ "$1" = "" ] && com=./COMMANDS/yarr
+ '[' python2.4 = '' ']'

ERROR_CHECK(){
	[ "$(echo ${PIPESTATUS[@]} | tr -d ' 0')" = "" ] && return

	echo $1
	rm -f $tmp-*
	exit 1
}

###########################################
#TEST1: no option use

cat << FIN > $tmp-in
山田
山本
田中
FIN
+ cat

cat << FIN > $tmp-out
山田 山本 田中
FIN
+ cat

${com} $tmp-in > $tmp-ans
+ python2.4 ./COMMANDS/yarr /tmp/10630-in
diff $tmp-ans $tmp-out
+ diff /tmp/10630-ans /tmp/10630-out
[ $? -eq 0 ] ; ERROR_CHECK "TEST1 error"
+ '[' 0 -eq 0 ']'
+ ERROR_CHECK 'TEST1 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

rm -f $tmp-*
+ rm -f /tmp/10630-ans /tmp/10630-in /tmp/10630-out
echo "${com}" OK
+ echo 'python2.4 ./COMMANDS/yarr' OK
exit 0
+ exit 0
+ ./nameread.test python2.4
#!/usr/local/bin/bash -xv
#
# test script of nameread
#
# usage: ./YARR.bash <python ver>

dir=$(dirname $0)/..
dirname $0)/..
dirname $0
++ dirname ./nameread.test
+ dir=./..
cd $dir
+ cd ./..

scr=./COMMANDS/nameread
+ scr=./COMMANDS/nameread
com="$1 ${scr}"
+ com='python2.4 ./COMMANDS/nameread'
[ "$1" = "" ] && com=./COMMANDS/nameread
+ '[' python2.4 = '' ']'

ERROR_CHECK(){
	[ "$(echo ${PIPESTATUS[@]} | tr -d ' 0')" = "" ] && return

	echo $1
	rm -f $tmp-*
	exit 1
}

tmp=/tmp/$$
+ tmp=/tmp/10640

cat << FIN > $tmp-name
A01 1
A02 2
A03 3
A10 5
FIN
+ cat

###########################################
#TEST1: ordinaly use

ANS=$( ${com} A01 $tmp-name )
 ${com} A01 $tmp-name )
 ${com} A01 $tmp-name 
++ python2.4 ./COMMANDS/nameread A01 /tmp/10640-name
+ ANS=1
[ "${ANS}" = "1" ] ; ERROR_CHECK "Test1 error"
+ '[' 1 = 1 ']'
+ ERROR_CHECK 'Test1 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

###########################################
#TEST2: regular expression

${com} -e '^A0[0-9]$' $tmp-name > $tmp-out
+ python2.4 ./COMMANDS/nameread -e '^A0[0-9]$' /tmp/10640-name

cat << FIN > $tmp-ans
1
2
3
FIN
+ cat

diff $tmp-ans $tmp-out ; ERROR_CHECK "Test2 error"
+ diff /tmp/10640-ans /tmp/10640-out
+ ERROR_CHECK 'Test2 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

###########################################
#TEST2: regular expression with output of names

${com} -el '^A0[0-9]$' $tmp-name > $tmp-out
+ python2.4 ./COMMANDS/nameread -el '^A0[0-9]$' /tmp/10640-name

cat << FIN > $tmp-ans
A01 1
A02 2
A03 3
FIN
+ cat

diff $tmp-ans $tmp-out ; ERROR_CHECK "Test3 error"
+ diff /tmp/10640-ans /tmp/10640-out
+ ERROR_CHECK 'Test3 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 0
++ tr -d ' 0'
+ '[' '' = '' ']'
+ return

rm $tmp-*
+ rm /tmp/10640-ans /tmp/10640-name /tmp/10640-out
echo "${com}" OK
+ echo 'python2.4 ./COMMANDS/nameread' OK
exit 0
+ exit 0
+ read com

rm -f $tmp-*
+ rm -f /tmp/10535-ver
exit 0
+ exit 0
