#!/usr/bin/env bash
#
# MANUAL2man : MANUAL ディレクトリ以下のテキスト・ファイルを man の形式に変換する。
# : written by 柳 日向 (h-yanagi@usp-lab.com; 2026/01/11)
#

version="Sun Jan 11 10:45:52 JST 2026"
edition=1

case "${1:-}" in
--version|--help)
	cat >&2 <<-EOF
Usage   : $(basename "$0")
Version : ${version}
Edition : ${edition}
	EOF
	exit 1
esac

version="$("$1" --version 2>&1 | fpad _ 3 | selr 1 Version | self 3/NF | xargs -I{} date -d "{}" +%Y%m%d)"

if hash gawk 2> /dev/null; then
	awk() { gawk "$@"; }
elif [ "$(uname)" = Darwin ]; then
	echo "GNU awk is required." >&2
	exit 1
fi

if [ "$(uname)" = Darwin ]; then
	alias date=gdate
fi

gawk -vname="$1" -vsection=1                                                                                 \
     -vversion_date="$(dayslash --output 'yyyy-mm-dd' 1 <<< "${version}" | LANG=C xargs -I{} date -d{} +"%d %b %Y")" \
     -vversion="${version}" -vspace="$(echo -ne '\r\xe2\x80\x89')" '
	/^(- ?)+$/ { next }

	NR == 1 {
		print ".TH ", "Tukubai", section, "\"" version_date "\"", "\"usp Tukubai\"", "\"Tukubai コマンド マニュアル\"";
		next;
	}

	match($0, /^(＜(.+)＞(.*)|([^%(（]+)）.+)$/, title) {
		gsub(/[＜＞]/, "", title[1]);
		gsub("）", " ", title[1]);

		print ".SH", title[1];

		if (title[3] != "") {
			printf " " title[2];
		}

		next;
	}

	/^\s*$/ {
		source = 0;
	}

	/^\$/ {
		print "";
		source = 1;
	}

	match($0, /^# ([0-9]{8}) (.+)$/, matches) {
		# 余談が開始したとき。

		if (digression != 1) {
			print "";
			print ".SH", "履歴";
		}

		digression = 1
		print " " substr(matches[1], 0, 4) "年" substr(matches[1], 5, 2) "月" substr(matches[1], 7, 2) "日 " matches[2];
		next;
	}

	/^ {8}/ {
		print;
		print ".br";
		next;
	}

	{
		gsub(/\\t/, " ", $0);
		gsub(/\\/, "\x5c", $0);
		$0 = gensub(/([^!-~]  +)([!-~]+) +([^!-~])/, "\\1" space "\\2" space "\\3", 1, $0);

		if (source) {
			print "  " $0;
			next;
		}

		gsub(/\\/, "\\\x5c");
		gsub(/<[^!][^>]+[^-]> *\n/, "\n.I \\0\\n", $0);
		gsub(/ /, "\\ ", $0);
		print $0;
		print ".br";
	}'
