#!/usr/bin/env gawk -f

BEGIN{
	for(i=1;i<=ARGC-1;i++){
		outp[i] = ARGV[i]
		ARGV[i] = ""
	}
}
{
	printf("%s",$(outp[1]))
	for(i=2;i<=ARGC-1;i++){
		if(outp[i] == "NF"){
			printf(" %s",$NF)
		}
		else
			printf(" %s",$(outp[i]))
	}
	print ""
}
