#!/usr/bin/env python
#coding: utf-8
#
# 1bai : 前0をとる（Open usp Tukubai版）
# 
# designed by Nobuaki Tounaka
# written  by Masatomo Togashi
#
# The MIT License
#
# Copyright (C) 2023 Universal Shell Programming Laboratory
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from __future__ import print_function
import re
import sys

_usage = "1bai [-r] [<f1> <f2> ...] [<file>]"
_usage2 = "1bai -d[r] string"
_usage3 = "1bai -[r]d string"
_version = "Thu Jan 19 03:12:32 JST 2023"
_code = "Open usp Tukubai (LINUX/PYTHON2.4+, 3.6/UTF-8)"
_keypat = r'((\d+|NF(-\d+)?)(/(\d+|NF(-\d+)?))?)(@((\d+|NF(-\d+)?)(/(\d+|NF(-\d+)?))?))*$'
_keypatNF=r'(?P<m0>(?P<m01>\d+)|(?P<m02>NF(?P<m03>-\d+)?))(/(?P<m1>(?P<m11>\d+)|(?P<m12>NF(?P<m13>-\d+)?)))?$'

def error(msg, *arg):
	print('Error[1bai] :', msg % arg, file=sys.stderr)
	sys.exit(1)

def usage():
	print("Usage   :", _usage, file=sys.stderr)
	print("        :", _usage2, file=sys.stderr)
	print("        :", _usage3, file=sys.stderr)
	print("Version :", _version, file=sys.stderr)
	print("         ", _code, file=sys.stderr)
	sys.exit(1)

#
# 入力ファイルオープン
#
def open_file(n, mode = 'r'):
	filename = sys.argv[n]	# 指定位置のコマンドパラメータをとる
	if filename == '-':	# sys.stdinのとき
		filename = '/dev/fd/0'	# ファイルディスクリプターで表記する
	if not Python3():
		mode='rU'	# Python2ではmodeがrUのときPython3と同様に読み込み時に各種改行記号がLF（\n）に統一される
	# 標準入力も含めてopen()で開く
	try:
		file = open(filename, mode)
		del sys.argv[n]
	except:
		if filename != '/dev/fd/0':
			file = open('/dev/fd/0', mode)	# 通常ファイルのopen()で失敗したらsys.stdinを開く
	return file

# 不要な空白の削除関数
def rm_sp(line):
	return re.sub(r' {2,}',' ',re.sub(r'^ +| +$','',line))	# 行頭と行末の空白を削除し連続空白を単空白にする

# 改行符号（\r\n）の削除関数
def rm_eol(line):
	return line.rstrip("\r\n")	# 改行記号としてCRLF('\r\n')/CR('\r')/LF('\n')のすべてに対応する

# BOMの取得関数
def get_BOM():
	if Python3():	return chr(int("FEFF",16))	# U+FEFFはBOMのUnicode符号位置
	else:			return "\xEF\xBB\xBF"	# BOMは「EF BB BF」の3バイト

# BOMの削除関数
def rm_BOM(line):
	global firstline
	if not firstline: return line
	firstline=False
	if line.startswith(get_BOM()):	line=line[len(get_BOM()):]	# 行頭にBOMがあったらBOMを削除する
	return line

# ファイル入力行の前処理
def preproc_line(line):
	line=rm_eol(line)	# 行末の改行記号を削除する
	line=rm_BOM(line)	# ファイル先頭行の行頭にBOMがあったらこれを削除する
	line=rm_sp(line)	# 行頭と行末の空白を削除し連続空白を単空白にする
	return line

# Python3か判定する
def Python3():
	if sys.version_info >= (3, 0):
		return True
	else:
		return False

# NF相対欄位置からNF（欄数）に応じた0発進の欄位置に変換する
def getpos(base_pos):
	# NF相対欄位置からの変換:
	#  nのときはそのまま
	#  0のときはNF（欄数）
	#  -nのときはNF-n
	# 0発信とするために-1を加える
	if base_pos > 0:
		pos=base_pos-1
		if pos >= NF:	error("フィールド番号が大きすぎます。 %s",str(base_pos))
		return False,pos	# 元からの絶対欄位置
	else:
		pos=NF+base_pos-1
		if pos < 0:	error("フィールド指定でNF-x の x が大きすぎます。 %s","NF-"+str(-base_pos))
		return True,pos	# NF相対欄位置からの絶対化欄位置
	return pos

# NF相対欄位置リスト（rel_keylist）からNF（欄数）に応じた実際の欄位置リスト（keylist）を作成する
def make_keylist(rel_keylist,abs_rel_mixed_range):
	# NF相対欄位置リスト（rel_keylist）とは「NFやNF-xのNF相対欄位置指定を含む欄位置リスト」を意味しリストには絶対欄位置も含む
	# rel_keylistの要素には区間をあらわす整数tupleの(start,end)と、単一欄をあらわす整数がある
	# rel_keylistを構成するそれぞれの整数は絶対欄位置指定とNF相対欄位置指定の両方がありうる
	if rel_keylist==[None]:	# 全欄指定
		return list(range(0,NF)),False
	rel_list=[]	# key指定順に並べたNF相対からの絶対化欄位置リスト
	abs_list=[]	# key指定順に並べた絶対欄位置リスト
	abs_rel_cross=False
	range_list=[]
	for fieldpos in rel_keylist:
		if type(fieldpos)==int:	# 単一欄
			rel,pos=getpos(fieldpos)
			if rel:
				rel_list.append(pos)
			else:
				abs_list.append(pos)
		else:	# (a/b)の区間指定
			rel1,start=getpos(fieldpos[0])
			rel2,end=getpos(fieldpos[1])
			if start <= end:	# 正順
				range_list=range(start,end+1)
			else:	# 逆順
				range_list=range(start,end-1,-1)
			if rel1 or rel2:	# 区間の端にNF相対襴位置指定があった
				rel_list+=range_list	# 片端のみがNF相対襴位置指定のときも便宜的にrel_listに加える
			else:
				abs_list+=range_list
	if abs_rel_mixed_range:	pass	# 絶対欄位置指定とNF相対欄位置指定による区間指定があるときは交叉検査をしない
	elif len(abs_list)*len(rel_list)==0:	pass	# 絶対欄位置指定群/NF相対欄位置指定群いずれかがないときは交叉検査をしない
	else:	# 両群ともに存在するときは交叉検査をする
		min_abs=min(abs_list)
		max_abs=max(abs_list)
		min_rel=min(rel_list)
		max_rel=max(rel_list)
		if max_abs < min_rel or max_rel < min_abs:	pass	# 両群が交叉しない
		else:	# 両群が交叉する
			abs_rel_cross=True
	# 返値のリストを整理する
	abs_and_rellist=abs_list+rel_list
	# 重複を解消しkey指定の順序はabs_list→rel_listの順としabs_list内とrel_list内の順序もそれぞれ保つ
	return_list=sorted(set(abs_and_rellist),key=abs_and_rellist.index)
	return return_list,abs_rel_cross	# 欄位置は0発進 集合化によってリストの重複を解消しkey指定の順序は保つ

# 欄番号文字列をNF相対形式で整数化する
def getFieldNum(str,str1,str2):
	# n または NF または NF-x の形式の欄番号をNF相対形式の整数で確定する
	# 正規表現で「\d+|NF(-\d+)?」にmatchする全体をstrが、「\d+」でmatchする部分をstr1が、「(-\d+)?」でmatchする部分をstr2が保持している
	# NF相対形式の整数化:
	#  単独のnが0のときはNone
	#  単独のnが0以外のときは整数のn
	#  単独のNFのときは整数の0
	#  NF-nのときは整数の-n
	# 実際の欄番号にする際には行ごとに得たNF（欄数）を使用して計算する
	if str1:	# n
		fieldnum=int(str1)
		if fieldnum==0:	# 欄番号0は全欄指定を意味する
			fieldnum=None
	else:	# NF-n または NF
		if str2:	# NF-n
			fieldnum=int(str2)
		else:	# NF
			fieldnum=0
	return fieldnum

#
# ひとつの欄指定パラメータから欄番号リストを得る（区間指定にも対応する）
#
def getFieldList(field_param):
	mobj = re.match(_keypat,field_param)	# 構文検査のために実行する
	if not mobj:	# フィールド指定の形式が不正
		error("フィールド指定の形式が不正です。 %s",field_param)
	field_param=field_param.replace("NF-0","NF")	# NF-0はNFと書き替える
	fieldlist=[]
	abs_rel_mixed_range=False
	concatlist=field_param.split("@")	# @で分割する
	for fieldnum in concatlist:
		mobj = re.match(_keypatNF,fieldnum)
		start=getFieldNum(fieldnum,mobj.group('m01'),mobj.group('m03'))	# 前端部を得る
		if mobj.group('m1'):	# a/bの形式で区間指定をしている
			end=getFieldNum(fieldnum,mobj.group('m11'),mobj.group('m13'))	# 後端部を得る
			fieldlist.append((start,end))	# 区間で確定
			# 絶対欄位置指定とNF相対欄位置指定が混在するときはmarkする
			if (start>0 and end <=0) or (start<=0 and end >0):
				abs_rel_mixed_range=True
		else:
			fieldlist.append(start)	# 前端部単独で確定
	return fieldlist,abs_rel_mixed_range

#
#	コマンドのフィールド指定パラメータリストから処理対象のNF相対欄位置リストを作成する
#
def getTargetFields(args):
	if args==[]:
		return [None],False	# フィールド指定パラメータリストが空のときは全欄指定とする
	abs_rel_mixed_range=False
	fieldlist = []
	for e in args:
		# getFieldList()は(fieldのlist,abs_rel_mixed_range)を返す
		fieldlist+=getFieldList(e)[0]
		if getFieldList(e)[1]==True:	abs_rel_mixed_range=True
	if None in fieldlist:
		return [None],False	# 欄位置にひとつでも0を指定するものがあるときは全欄指定とする
	# 集合化によってリストの重複を解消する（絶対欄位置/NF相対欄位置それぞれに重複解消される）
	fieldlist=sorted(set(fieldlist), key=fieldlist.index)	# 元のリスト（set）における出現順を維持する
	return fieldlist,abs_rel_mixed_range

#
# 行の欄数検査
#   先頭行ではkeyの区間指定で絶対欄位置指定とNF相対欄位置指定が混在しているか検査する
#   先頭行以外では
#     絶対欄位置リストとNF相対欄位置絶対化リスト（区間の端がNF相対襴位置だったものも含む）の間に重複があるか検査する
#
def check_num_fields_variation(fields):
	global	NF,key_list,abs_rel_cross_first,abs_rel_cross,abs_rel_mixed_range
	# abs_rel_cross キーの絶対欄位置によるリストとNF相対欄位置からの絶対化欄位置リストの間に重複があればTrue
	#               NF=5のときにキー指定が「1/4@NF-3/NF」となっているときなどにTrueとなる
	# abs_rel_cross_first=False 先頭行においてabs_rel_crossがTrueであればTrue

	start=False
	nf=len(fields)
	if NF==-1:	start=True
	if nf != NF:	# 欄数が変化したかまたは先頭行なら
		NF=nf	# NFを更新
		# 行の欄数NFを見てNF相対欄位置リストから(絶対)欄位置リストを決定する
		key_list,abs_rel_cross=make_keylist(rel_keylist,abs_rel_mixed_range)
		if start:	# 先頭行なら
			if abs_rel_cross:	abs_rel_cross_first=True	# 先頭行において区間指定でabs_rel混在だったらmarkしておく
			else:	abs_rel_cross_first=False
		else:	# 先頭行以外で欄数変化があったら
			if abs_rel_mixed_range:	# 区間指定においてabs_rel混在だったら
				error("keyの区間指定において絶対欄位置指定とNF相対欄位置指定が混在している状態でフィールド数が変化しました。")
			if abs_rel_cross_first or abs_rel_cross:	# （区間指定においてabs_rel非混在で）絶対欄位置指定とNF相対欄位置指定に交叉が生じたら
				error("フィールド数変化に際してkeyの絶対欄位置指定とNF相対欄位置指定に交叉がありました。")
	return

# 前0の削除/小数点以下の後0の削除/符号処理/-r指定による正負反転
def CripZero(field,r):
	# format検査
	try:
		float(field)
	except:
		error("%sは数値ではありません",field)
	if field.upper().find("E")>0: # 浮動小数点数は排除する
		error("%sは整数でも固定小数点数でもありません",field)

	# 負符号の記憶と削除
	negative=False
	if field[0]=="-":
		negative=True
		field=field.lstrip("-")

	# 正符号の削除
	else: field=field.lstrip("+")

	# 前0と後0の削除
	field=field.lstrip("0") # 前0の削除
	if field.startswith("."): field="0"+field # 小数点で始まるときは前に0を付ける
	if field.find(".")>=0:    field=field.rstrip("0") # 小数点を含むとき後0を削除
	field=field.rstrip(".") # 小数点で終るときは整数とする
	if field=="": return "0" # 0ならそのまま返す

	# 負符号を復元する
	if negative: field="-"+field

	# 正負反転
	if r: # 指定あり
		# 数値化し正負反転し文字列に戻す
		if field.find(".")>0: # 小数点付き
			field=str(-float(field))
		else: # 整数
			field=str(-int(field))

	return field

#
# 直接入力文字列の前処理
#
#  Python3においてコマンドラインからの直接入力文字列中にUnicode符号位置がU+FFFFを超えるコードがあると
#  Unicode文字に正しく変換されない場合があることへの対処をする
#  Unicode符号位置がU+FFFFを超えるコードを含む文字列は数値を表すことはないのでエラーメッセージを正しく出力するための措置
def utf2ucs(instr):
	outstr=""	# 出力文字列
	intlist=[]	# 作業用整数リスト
	for char in instr:
		if ord(char)>=0xdc00 and ord(char)<=0xdcff:	# 文字の符号位置がU+DCxxの範囲にあったら「UTF8もどき」
			intlist.append(ord(char)-0xdc00)	# 0xdc00のげたをはずして整数リストに入れる
		else:	# 通常文字がきたら
			if len(intlist)>0:	# ここまでに「UTF8もどき」列を変換した整数リストがあったら
				# bytesに変換してutf8からUCSへの変換をして出力文字列に追加
				outstr+= bytes(intlist).decode("utf_8")
				intlist=[]	# 整数リストを再初期化
			outstr+=char	# 新しくきた通常文字を出力文字列に追加
	# 「UTF8もどき」列を変換した整数リストが残っていたら
	# bytesに変換してutf8からUCSへの変換をして出力文字列に追加
	if len(intlist)>0:	outstr+= bytes(intlist).decode("utf_8")
	return outstr

# main

if __name__ == '__main__':

	global NF,key_list,abs_rel_cross_first,abs_rel_cross
	r,d = False, False # default値

	# コマンドの説明表示
	if len(sys.argv) <= 1 \
	 or sys.argv[1] == '--help' \
	 or sys.argv[1] == '--version':
		usage()

	# パラメータ解析
	numparam=0
	minparam=1
	argc = len(sys.argv)
	for i in range(argc-1,-1,-1):	# パラメータ列を後方から前方へ処理する
		if i==0:
			del sys.argv[0]
		elif sys.argv[i].startswith("-r"): # -rで始まるオプション
			if r:
				error("-rオプションが重複しています")
			else: r=True
			if sys.argv[i][2:]=="d": # -rdオプション
				if d:
					error("-dオプションが重複しています")
				d=True
			elif not sys.argv[i]=="-r": # -rオプション
				error("%sは無効なオプションです",arg)
			del sys.argv[i]
		elif sys.argv[i].startswith("-d"): # -dで始まるオプション
			if d:
				error("-dオプションが重複しています")
			else: d=True
			if sys.argv[i][2:]=="r": # -drオプション
				if r:
					error("-rオプションが重複しています")
				r=True
			elif not sys.argv[i]=="-d": # -dオプション
				error("%sは無効なオプションです",arg)
			del sys.argv[i]
		else:
			numparam+=1

	# パラメータ検査
	if numparam<minparam:
		error("パラメータの数が足りません")

	# ファイルに対する処理
	if not d:
		# 入力ファイルを開く
		file=open_file(len(sys.argv)-1)	# パラメータ列の最後尾をファイル名と仮定してopenできたら最後尾は削除する
		# フィールド指定パラメータからNF相対欄位置リストを作成する
		rel_keylist,abs_rel_mixed_range = getTargetFields(sys.argv)	# sys.argvに残っているのはフィールド指定のみ
		# 先頭行処理用flagの初期化
		NF=-1
		firstline=True
		for line in file: # 入力ファイルを読む
			line=preproc_line(line)
			inputfields=line.split(" ")
			check_num_fields_variation(inputfields)	# 先頭行または欄数変化のあるときはkey指定の検査をする
			# 指定フィールドに対して前0の削除/小数点以下の後0の削除/符号処理/正負反転処理をする
			for fieldnum in key_list:
				inputfields[fieldnum]=CripZero(inputfields[fieldnum],r)
			print(" ".join(inputfields))	# フィールドを空白区切りで出力する
	# -d指定で文字列に対する直接処理
	else:
		if numparam>1:
			error("d指定で余分なパラメータがあります")
		string=sys.argv.pop() # -r/-d以外のパラメータ列最後尾のファイル名相当部を入力文字列とする
		if Python3():
			string=utf2ucs(string)	# Python3のときは-d指定の文字列に対して前処理をする
		print(CripZero(string,r))

	# 終了
	sys.exit(0)
