#!/usr/bin/env python
#coding: utf-8
#
# comma カンマを振る（Open usp Tukubai版）
# 
# designed by Nobuaki Tounaka
# written  by Masatomo Togashi
#
# The MIT License
#
# Copyright (C) 2022 Universal Shell Programming Laboratory
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from __future__ import print_function

_usage = "comma [+<n>h][-4] [<f1> <f2> ...] <file>"
_usage1 = "comma -d[4] <string>"
_version = "Thu Apr 21 00:58:47 JST 2022"
_code = "Open usp Tukubai (LINUX+FREEBSD/PYTHON2.4/UTF-8)"
_keypat = r'((\d+|NF(-\d+)?)(/(\d+|NF(-\d+)?))?)(@((\d+|NF(-\d+)?)(/(\d+|NF(-\d+)?))?))*$'
_keypatNF=r'(?P<m0>(?P<m01>\d+)|(?P<m02>NF(?P<m03>-\d+)?))(/(?P<m1>(?P<m11>\d+)|(?P<m12>NF(?P<m13>-\d+)?)))?$'

import re
import os
import sys
import types

def error(msg, *arg):
	print('Error[comma] :', msg % arg, file=sys.stderr)
	sys.exit(1)

def usage():
	print("Usage   :", _usage, file=sys.stderr)
	print("        :", _usage1, file=sys.stderr)
	print("Version :", _version, file=sys.stderr)
	print("         ", _code, file=sys.stderr)
	sys.exit(1)

#
# 入力ファイルオープン
#
def open_file(n, mode = 'r'):
	if n >= len(sys.argv):	# ファイル名省略時
		filename = '-'	# sys.stdinを仮定する
	else:
		filename = sys.argv[n]	# 指定位置のコマンドパラメータをとる
	if filename == '-':	# sys.stdinのとき
		filename = '/dev/fd/0'	# ファイルディスクリプターで表記する
	if not Python3():
		mode='rU'	# Python2ではmodeがrUのときPython3と同様に読み込み時に各種改行記号がLF（\n）に統一される
	# 標準入力も含めてopen()で開く
	try:
		file = open(filename, mode)
		del sys.argv[n]
	except:
		if filename != '/dev/fd/0':
			file = open('/dev/fd/0', mode)	# 通常ファイルのopen()で失敗したらsys.stdinを開く
	return file

# NF相対欄位置からNF（欄数）に応じた0発進の欄位置に変換する
def getpos(base_pos):
	# NF相対欄位置からの変換:
	#  nのときはそのまま
	#  0のときはNF（欄数）に
	#  -nのときはNF-nに
	# 0発進とするために-1を加える
	if base_pos > 0:
		pos=base_pos-1
		if pos > NF-1:	error("フィールド番号が大きすぎます。 %s",str(base_pos))
	else:
		pos=NF+base_pos-1
		if pos < 0:	error("フィールド指定で NF-x の x が大きすぎます。 %s","NF-"+str(-base_pos))
	return pos

# NF相対欄位置リスト（base_keylist）からNF（欄数）に応じた実際の欄位置リスト（keylist）を作成する
def make_keylist(base_keylist):
	# base_keylistの要素には区間をあらわす整数tupleの(start,end)と、単一欄をあらわす整数がある
	if base_keylist==[None]:	# 全欄指定
		return list(range(0,NF))
	keylist=[]
	for fieldpos in base_keylist:
		if type(fieldpos)==int:	keylist.append(getpos(fieldpos))	# 単一欄
		else:	# (a/b)の区間
			start=getpos(fieldpos[0])
			end=getpos(fieldpos[1])
			if start <= end:	# 正順
				keylist+=range(start,end+1)
			else:	# 逆順
				keylist+=range(start,end-1,-1)
	return list(set(keylist))	# 欄位置は0発進

# 欄番号文字列をNF相対形式で整数化する
def getFieldNum(str,str1,str2):
	# n または NF または NF-x の形式の欄番号をNF相対形式の整数で確定する
	# 正規表現で「\d+|NF(-\d+)?」にmatchする全体をstrが、「\d+」でmatchする部分をstr1が、「(-\d+)?」でmatchする部分をstr2が保持している
	# NF相対形式の整数化:
	#  単独のnが0のときはNone
	#  単独のnが0以外のときは整数のn
	#  単独のNFのときは整数の0
	#  NF-nのときは整数の-n
	# 実際の欄番号にする際には行ごとに得たNF（欄数）を使用して計算する
	if str1:	# n
		fieldnum=int(str1)
		if fieldnum==0:	# 欄番号0は全欄指定を意味する
			#error("フィールド指定に0があります。")
			fieldnum=None
	else:	# NF-n または NF
		if str2:	# NF-n
			fieldnum=int(str2)
		else:	# NF
			fieldnum=0
	return fieldnum

#
# ひとつの欄指定パラメータから欄番号リストを得る（区間指定にも対応する）
#
def getFieldList(field_param):
	mobj = re.match(_keypat,field_param)	# 構文検査のために実行する
	if not mobj:	# フィールド指定の形式が不正
		error("フィールド指定の形式が不正です。 %s",field_param)
	fieldlist=[]
	concatlist=field_param.split("@")	# @で分割する
	for fieldnum in concatlist:
		mobj = re.match(_keypatNF,fieldnum)
		start=getFieldNum(fieldnum,mobj.group('m01'),mobj.group('m03'))	# 前端部を得る
		if mobj.group('m1'):	# a/bの形式で区間指定をしている
			end=getFieldNum(fieldnum,mobj.group('m11'),mobj.group('m13'))	# 後端部を得る
			fieldlist.append((start,end))	# 区間で確定
		else:
			fieldlist.append(start)	# 前端部単独で確定
	return fieldlist

#
#	コマンドのフィールド指定パラメータリストから処理対象のNF相対欄位置リストを作成する
#
def getTargetFields(args):
	if args==[]:
		return [None]	# フィールド指定パラメータリストが空のときは全欄指定とする
	ans = []
	for e in args:
		ans+=getFieldList(e)
	if None in ans:
		return [None]	# 欄位置にひとつでも0を指定するものがあるときは全欄指定とする
	ans=list(set(ans)) # 集合化によってリストの重複を解消する
	return ans

#
# カンマ付け
#
def comma(str, four):
	if four:
		l = 4
	else:
		l = 3

	if Python3():
		flags=re.ASCII	# Python3でもPython2と同様に数字は[0-9]に限る
	else:
		flags=0
	r=re.match(r'[-+]?((\d+)(\.\d*)?|\.\d+)([eE][-+]?\d+)?\Z',str,flags)
	if not r: error("フィールド値が数値の形式ではありません。")
	return str[:r.start(2)]+re.sub('^,','',re.sub('(\d{%d})' % l, r'\1,', r.group(2)[::-1])[::-1])+str[r.end(2):]

# 改行符号（\r\n）の削除関数
def rm_eol(line):
	return line.rstrip("\r\n")	# 改行記号としてCRLF('\r\n')/CR('\r')/LF('\n')のすべてに対応する

# BOMの取得関数
def get_BOM():
	if Python3():	return chr(int("FEFF",16))	# U+FEFFはBOMのUnicode符号位置
	else:			return "\xEF\xBB\xBF"	# BOMは「EF BB BF」の3バイト

# BOMの削除関数
def rm_BOM(line):
	global firstline
	if not firstline: return line
	firstline=False
	if line.startswith(get_BOM()):	line=line[len(get_BOM()):]	# 行頭にBOMがあったらBOMを削除する
	return line

# ファイル入力行の前処理
def preproc_line(line):
	line=rm_eol(line)	# 行末の改行記号を削除する
	line=rm_BOM(line)	# ファイル先頭行の行頭にBOMがあったらこれを削除する
	return line

# Python3か判定する
def Python3():
	if sys.version_info >= (3, 0):
		return True
	else:
		return False

#
# メイン関数
#
if __name__ == '__main__':

	if len(sys.argv) < 2 \
	 or sys.argv[1] == '--help' \
	 or sys.argv[1] == '--version':
		usage()

	#
	# -d[4]
	#
	if re.match(r'-d4?$', sys.argv[1]):
		if len(sys.argv) != 3:
			usage()
		print(comma(sys.argv[2], sys.argv[1][-1] == '4'))
		sys.exit(0)

	#
	# +<n>h
	#
	if re.match(r'\+\d*h$', sys.argv[1]):
		if len(sys.argv[1]) == 2:
			header = 1
		else:
			header = int(sys.argv[1][1:-1])
			if header == 0:
				header = 1
		del sys.argv[1]
		if len(sys.argv) < 2:
			usage()
	else:
		header = 0

	#
	# -4
	#
	if sys.argv[1] == '-4':
		four = True
		del sys.argv[1]
		if len(sys.argv) < 2:
			usage()
	else:
		four = False

	if len(sys.argv) < 2:	# 未処理のパラメータが残っていなければエラー
		usage()

	#
	# 入力ファイルのオープン
	#
	file = open_file(len(sys.argv) - 1)

	# フィールド指定パラメータからNF相対欄位置リストを作成する
	rel_keylist = getTargetFields(sys.argv[1:])	# sys.argvに残っているのはコマンド名とフィールド指定のみ

	# 先頭行処理用flagの初期化
	firstline=True

	#
	# ヘッダー処理
	#
	for i in range(header):
		line = file.readline()
		if not line:
			sys.exit(0)
		line = preproc_line(line)
		fields = line.split()
		print(line)	# defaultの改行で出力する

	#
	# メインループ
	#
	for line in file:
		line = preproc_line(line)
		fields = line.split()
		NF=len(fields)

		# 行の欄数に応じてrel_keyからkeyを決定する
		key=make_keylist(rel_keylist)

		#
		# カンマ処理
		#

		endchar=' '
		for i in range(0, NF):
			if i==NF-1: endchar=''
			if i in key:
				print(comma(fields[i], four),end=endchar)
			else:
				print(fields[i],end=endchar)
		print()

	sys.exit(0)
