#!/usr/bin/env python
#coding: utf-8
# 
# gyo（Open usp Tukubai版）
#
# designed by Nobuaki Tounaka
# written  by Hinata Yanagi
#
# The MIT License
#
# Copyright (C) 2022 Universal Shell Programming Laboratory
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from __future__ import print_function

_usage = "gyo [-f] [<file> ...]"
_version = "Tue Sep  6 08:55:48 JST 2022"
_code = "Open usp Tukubai (LINUX+FREEBSD/PYTHON2.4+/UTF-8)"

import os
import sys
import codecs

def printUsage():
	print("Usage   :", _usage, file=sys.stderr)
	print("Version :", _version, file=sys.stderr)
	print("         ", _code, file=sys.stderr)
	sys.exit(1)

def prefixEqual(prefix,token):
	if len(prefix) > len(token):	return False
	
	p = token[0:len(prefix)]
	if p == prefix:	return True

	return False

def die(message):
	print("Error[gyo] :", message, file=sys.stderr)
	sys.exit(1)

def count(filename):
	file = None
	if filename == "-":
		filename = '/dev/fd/0' # sys.stdinをファイルディスクリプターで表記する
	elif not os.path.exists(filename) or os.path.isdir(filename):
		die(filename + ":ファイルがありません。")
	elif os.path.isdir(filename):
		return 0
	if Python3(): mode='r'
	else:	mode='rU' # Python2ではmodeがrUのときPython3と同様に読み込み時に各種改行記号がLF（\n）に統一される
	try:
		file = open(filename,mode)
	except IOError:
		die(filename + ":ファイルが開けません。")
	if file == None: return 0

	n = 0
	for line in file: n += 1

	file.close()
	return n

# Python3か判定する
def Python3():
	if sys.version_info >= (3, 0):
		return True
	else:
		return False

###########################################
# メイン関数
###########################################
if __name__ == '__main__':

	###########################################
	# オプションの処理
	###########################################
	mode = "normal"
	files = []
	argc = len(sys.argv)

	# 構文表示
	if len(sys.argv) == 2:
		if sys.argv[1] == '--help' or \
		   sys.argv[1] == '--version': printUsage()

	for i in range(1, argc):
		arg = sys.argv[i]
		if arg == "-f":  mode = "file"
		elif arg == "-": files.append(arg)
		else:            files.append(arg)

	if len(files) == 0:
		files.append("-")

	###########################################
	# 出力
	###########################################
	for f in files:
		n = count(f)
		if n != None:
			if mode == "normal": print(n)
			else:                print(f,n)
