#!/usr/bin/env python
#coding: utf-8
#
# juni 順位をつける（Open usp Tukubai版）
# 
# designed by Nobuaki Tounaka
# written  by Hinata Yanagi
#
# The MIT License
#
# Copyright (C) 2022 Universal Shell Programming Laboratory
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from __future__ import print_function

_usage = "juni [<k1> <k2>] [<file>]"
_usage1 = "juni -h [<k1> <k2>] [<file>]"
_version = "Mon Aug 29 07:54:58 JST 2022"
_code = "Open usp Tukubai (LINUX+FREEBSD/PYTHON2.4/UTF-8)"
_keypat = r'\d+$'

# 濁音と半濁音のNFD表記でNFC表記もできるもの→NFDtoNFC変換でNFCに統一する
_comb_pat=r"(((う|か|き|く|け|こ|さ|し|す|せ|そ|た|ち|つ|て|と|は|ひ|ふ|へ|ほ|ウ|カ|キ|ク|ケ|コ|サ|シ|ス|セ|ソ|タ|チ|ツ|テ|ト|ハ|ヒ|フ|ヘ|ホ|ワ|ヰ|ヱ|ヲ)゙)|((は|ひ|ふ|へ|ほ|ハ|ヒ|フ|ヘ|ホ)゚))+"

import re
import os
import sys
from getopt import getopt
import unicodedata

def error(msg, *arg):
	print('Error[juni] :', msg % arg, file=sys.stderr)
	sys.exit(1)

def usage():
	print("Usage   :", _usage, file=sys.stderr)
	print("        :", _usage1, file=sys.stderr)
	print("Version :", _version, file=sys.stderr)
	print("        :", _code, file=sys.stderr)
	sys.exit(1)

class FieldLine:
	def __init__(self, line, allow_z = False):
		self.__allow_zero = allow_z
		self.__fields = [ line ]
		self.__fields += [ x for x in line.split(' ') if x ]

	def size(self):
		return len(self.__fields) - 1

	def getField(self, s, e = None):
		if e == None:
			e = s
		if s > self.size() or e > self.size():	error("フィールド番号が大きすぎます。")
		if s <= e:
			return ' '.join(self.__fields[s : e + 1])
		else:
			t = self.__fields[e : s + 1]
			t.reverse()
			return ' '.join(t)

#
# 入力ファイルオープン
#
def open_file(n):
	if type(n) == type(0):
		if n >= len(sys.argv):	n = '-'
		else:	n = sys.argv[n]
	if n == '-':	n = '/dev/fd/0'	# sys.stdinをファイルディスクリプターで表記する
	if Python3():	mode='r'
	else:	mode='rU'	# Python2ではmodeがrUのときPython3と同様に読み込み時に各種改行記号がLF（\n）に統一される
	try:
		file = open(n, mode)
	except:
		if n=='/dev/fd/0': n="-"
		error("ファイル '%s' をオープンできません。", n)
	return file

# 改行符号（\r\n）の削除関数
def rm_eol(line):
	return line.rstrip("\r\n")	# 改行記号としてCRLF('\r\n')/CR('\r')/LF('\n')のすべてに対応する

# BOMの取得関数
def get_BOM():
	if Python3():	return chr(int("FEFF",16))	# U+FEFFはBOMのUnicode符号位置
	else:			return "\xEF\xBB\xBF"	# BOMは「EF BB BF」の3バイト

# BOMの削除関数
def rm_BOM(line):
	global firstline
	if not firstline: return line
	firstline=False
	if line.startswith(get_BOM()):	line=line[len(get_BOM()):]	# 行頭にBOMがあったらBOMを削除する
	return line

# ファイル入力行の前処理
def preproc_line(line):
	line=rm_eol(line)	# 行末の改行記号を削除する
	line=rm_BOM(line)	# ファイル先頭行の行頭にBOMがあったらこれを削除する
	return line

# Python3か判定する
def Python3():
	if sys.version_info >= (3, 0):
		return True
	else:
		return False

#
# unicode 変換
#
def to_unicode(s):
	try:
		return unicode(s, 'utf_8')
	except:
		error("不当なマルチバイト文字が含まれています。")

#
# utf8 変換
#
def to_utf8(s):
	try:
		return s.encode('utf-8')
	except:
		error("内部エラー UTF8への変換に失敗しました。")

#
# NFDtoNFC()のre.sub()から指定patternがみつかるごとに呼ばれるのでNFD/NFC変換をして返す
# 置換対象パターンはNFD文字:全角ひらがな/全角カタカナの清音に結合用濁点/結合用半濁点を連接したもの
# 置換先文字はNFC文字:全角ひらがな/全角カタカナの濁音/半濁音
#
def replace(matchobj):
	if Python3():	return unicodedata.normalize('NFC',matchobj.group(0))
	else:	return to_utf8(unicodedata.normalize('NFC',to_unicode(matchobj.group(0))))	# Python2ではutf8→unicdoe→utf8の変換をする

#
# 全角ひらがな/全角カタカナの濁音/半濁音のNFC化
#
def NFDtoNFC(str):
	# 全角ひらがな/全角カタカナの濁音/半濁音をNFCで統一して返す
	return re.sub(pattern,replace,str)

#
# メイン関数
#
if __name__ == '__main__':
	#
	# 引数がない場合は標準入力を読み込むファイルとなる。
	#
	if  len(sys.argv) == 1:
			sys.argv.append('-')

	# 構文表示
	if len(sys.argv) < 2: usage()
	elif len(sys.argv) == 2:
		if sys.argv[1] == '--help' or \
		   sys.argv[1] == '--version':	usage()

	#
	# NFD文字（清音+結合用濁点/結合用半濁点）検出のための正規表現パターンを準備
	#
	pattern=re.compile(_comb_pat)

	#
	# -h
	#
	try:
		opts = getopt(sys.argv[1:], "h")
		if opts[0]:
			h_mode = True
		else:
			h_mode = False
		sys.argv = [ sys.argv[0] ] + opts[1]
	except:
		usage()

	firstline=True

	#
	# juni -h [<k1> <k2>] <file>
	#
	if h_mode:
		if len(sys.argv) <= 2:	# juni h <file>
			n = None
			file = open_file(1)	# <file>省略時は標準入力を仮定する
		elif len(sys.argv) > 4:
			usage()
		else:	# juni h <k1> <k2> <file>
			if not re.match(_keypat, sys.argv[1]) \
			 or not re.match(_keypat, sys.argv[2]):
				usage()
			k1 = int(sys.argv[1])
			k2 = int(sys.argv[2])
			if k1 == 0 or k2 ==0:
				error("フィールド番号が正しくありません。")
			n = [ 0 ] * (k2 + 1)
			oldkey = [ None ] * (k2 + 1)
			file = open_file(3)	# <file>省略時は標準入力を仮定する
		for line in file:
			line=preproc_line(line)	# 入力行の前処理
			line = FieldLine(line)
			if not n:
				k1 = 1
				k2 = line.size()
				if k2 == 0:
					error("先頭行が空行です。")
				n = [ 0 ] * (k2 + 1)
				oldkey = [ None ] * (k2 + 1)
			elif line.size() < k2:
				error("フィールドが足りません。")
			for i in range(k1, k2 + 1):
				key= NFDtoNFC(line.getField(i))
				if key != oldkey[i]:
					n[i] += 1
					oldkey[i] = key
					for i in range(i + 1, k2 + 1):
						n[i] = 1
						oldkey[i] = NFDtoNFC(line.getField(i))
					break
			print(' '.join([ str(x) for x in n[k1:] ]), line.getField(0))
		sys.exit(0)

	#
	# juni <file>
	#
	if len(sys.argv) <= 2:
		file = open_file(1)
		n = 1
		for line in file:
			line=preproc_line(line)	# 入力行の前処理
			print(n, line)	# lineは改行記号をとっている
			n = n + 1
		sys.exit(0)

	#
	# juni <k1> <k2> <file>
	#
	if len(sys.argv) > 4 \
	 or not re.match(_keypat, sys.argv[1]) \
	 or not re.match(_keypat, sys.argv[2]):
		usage()
	k1 = int(sys.argv[1])
	k2 = int(sys.argv[2])
	if k1 == 0 or k2 ==0:
		error("フィールド番号が正しくありません。")
	# 降順を昇順化
	if k1 > k2:	k1,k2=k2,k1
	file = open_file(3)	# <file>省略時は標準入力を仮定する
	oldkey = None
	for line in file:
		line=preproc_line(line)	# 入力行の前処理
		line = FieldLine(line)
		key = line.getField(k1, k2)
		key = NFDtoNFC(key)
		if key != oldkey:
			n = 1
			oldkey = key
		print(n, line.getField(0))
		n = n + 1

	sys.exit(0)
