#!/usr/bin/env python
#coding: utf-8
#
# lcalc: １０進演算を行う。 (Open usp Tukubai)
# 
# designed by Nobuaki Tounaka
# written  by Hinata Yanagi
# 
# The MIT License
# 
# Copyright (C) 2026 Universal Shell Programming Laboratory
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import ast
import sys
import math
import re

from decimal import Decimal, getcontext

_usage = "lcalc <script> <files>..."
_usage2 = "lcalc -d <script>"
_version = "Sun Jan 25 15:31:48 JST 2026"
_code = "Open usp Tukubai (LINUX/PYTHON2.4+, 3.6/UTF-8)"

optind = 1
alternatives = {
	"divzero"  : "div/0",
	"overflow" : "ovflw",
	"outdomain": "outdm"
}

getcontext().prec = 10 + 2

class UDecimal(Decimal):
	def __truediv__(self, divider):
		if int(divider) == 0:
			return UDecimal(0)
		else:
			return Decimal.__truediv__(self, divider)

	__div__ = __truediv__

def usage():
	sys.stderr.write("Usage   : " + _usage + "\n")
	sys.stderr.write("          " + _usage2 + "\n")
	sys.stderr.write("Version : " + _version + "\n")
	sys.stderr.write("          " + _code + "\n")
	exit(1)

def escape(value):
	return re.sub(' ', '_', re.sub('_', "\\_", str(value)))

def format_value(value):
	if type(value) in [Decimal, UDecimal]:
		return re.sub(r'^([0-9]+\.0)0*$', '\\1',
			re.sub(r'^([0-9]+\.[0-9]{0,9}[1-9])0*$', '\\1',
			re.sub(r'^([0-9]+\.[0-9]{1,10})[0-9]*$', '\\1',
			re.sub(r'^([0-9]+\.[0-9]{10}).*$', '\\1',
				format(value, ".%df" % 15)))))
	elif type(value) == bool:
		return "1.0" if value else "0.0"
	else:
		return value

for item in sys.argv[1:]:
	argument = re.match("^--(divzero|overflow|outdomain)(|=(.+))$", item)

	if argument is None:
		break

	optind += 1

	if argument.group(2) is None or argument.group(2) == "":
		continue

	alternatives[argument.group(1)] = argument.group(2)[1:]

if len(sys.argv) <= optind:
	usage()

def resolve_reference(record, capture):
	type_match = type(re.search(r'', '')) if sys.version_info[0] == 2 else re.Match
	nf_offset = re.match(r'^ *NF *(|- *([0-9]+))$', capture.group(1))
	field = None
	offset_string = re.sub(r' *NF *', str(len(record)), capture.group(1))

	if nf_offset is None:
		field = "UDecimal({})".format(record[eval(offset_string) - 1])
	elif nf_offset.group(1) == "":
		field = "UDecimal({})".format(record[len(record) - 1])
	else:
		field = "UDecimal({})".format(record[len(record) - int(nf_offset.group(1)) - 1])
	value = None
	if re.match(r'^0[0-9]+$', field):
		value = repr(field)
	elif type(capture) == type_match and re.match(r'^[0-9]+(\.[0-9]+)?$', field):
		value = "UDecimal({})".format(field)
	else:
		field_value = record[eval(offset_string) - 1]

		if re.match(r'^[1-9][0-9]*(|\.[0-9]+)$', field_value):
			# 数値を表現する文字列の場合のみ変換する。
			value = "UDecimal({})".format(field_value)
		else:
			value = repr(field_value)

	return value
	

def evaluate(expr, record):
	expression =                                                                        \
		"[{}]".format(                                                              \
			re.sub(r'\$([0-9]|NF|NF-[0-9]+|\(NF *- *[0-9]+\))', lambda capture: \
				str(resolve_reference(record, capture)), expr))
	try:
		NF = len(record)
		return eval(expression)
	except NameError:
		return expression
	except ZeroDivisionError:
		return alternatives["divzero"]

if "-d" == sys.argv[optind]:
	del sys.argv[optind]
	print(" ".join(map(str, format_value(evaluate(sys.argv[optind], [])))))
	exit()

if len(sys.argv) <= 1 or      \
   sys.argv[1] == '--help' or \
   sys.argv[1] == '--version':
	usage()

script = sys.argv[optind].split("#")[0]
optind += 1
files = list(map(lambda file_name: open(file_name, "r"), sys.argv[optind:]))

if files == []:
	files += [sys.stdin]

for file in files:
	for record in map(lambda line: re.split(r' +', line.rstrip()), file):
		print(" ".join(map(format_value, evaluate(script, record))))
