#!/usr/bin/env python
#coding: utf-8
#
# laclc: １０進演算を行う。 (Open usp Tukubai)
# 
# designed by Nobuaki Tounaka
# written  by Hinata Yanagi
# 
# The MIT License
# 
# Copyright (C) 2026 Universal Shell Programming Laboratory
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import ast
import sys
import math
import re

from decimal import Decimal

_usage = "lcalc <script> <files>..."
_usage2 = "lcalc -d <script>"
_version = "Sun Jan  4 09:49:03 AM JST 2026"
_code = "Open usp Tukubai (LINUX/PYTHON2.4+, 3.6/UTF-8)"

optind = 1
alternatives = {
	"divzero"  : "div/0",
	"overflow" : "ovflw",
	"outdomain": "outdm"
}

def usage():
	sys.stderr.write("Usage   : " + _usage + "\n")
	sys.stderr.write("          " + _usage2 + "\n")
	sys.stderr.write("Version : " + _version + "\n")
	sys.stderr.write("          " + _code + "\n")
	exit(1)

def escape(value):
	return re.sub(' ', '_', re.sub('_', "\\_", str(value)))

def format_value(value):
	if type(value) == Decimal:
		return re.sub(r'(\.........).*$', '\\1', format(value, ".12f"))
	else:
		return value

for item in sys.argv[1:]:
	argument = re.match("^--(divzero|overflow|outdomain)(|=(.+))$", item)

	if argument is None:
		break

	optind += 1

	if argument.group(2) is None or argument.group(2) == "":
		continue

	alternatives[argument.group(1)] = argument.group(2)[1:]

if len(sys.argv) <= optind:
	usage()

def resolve_reference(record, capture):
	field = record[int(capture.group(1)) - 1]
	
	if re.match(r'^0[0-9]+$', field):
		return repr(field)
	elif type(capture) == re.Match and re.match(r'^[0-9]+(\.[0-9]+)?$', field):
		return "Decimal({})".format(field)
	else:
		return repr(record[int(capture.group(1)) - 1])

def evaluate(expr, record):
	expression = re.sub(r'\$([0-9]|NF|NF-[0-9]+)', lambda capture: \
		str(resolve_reference(record, capture)), expr)

	try:
		return eval(expression)
	except NameError:
		return [expression]
	except ZeroDivisionError:
		return [alternatives["divzero"]]
	except:
		return ["@"]

if "-d" == sys.argv[optind]:
	del sys.argv[optind]
	print(evaluate(sys.argv[optind], []))
	exit()

if len(sys.argv) <= 1 or      \
   sys.argv[1] == '--help' or \
   sys.argv[1] == '--version':
	usage()

script = sys.argv[optind].split("#")[0]
optind += 1
files = map(lambda file_name: open(file_name, "r"), sys.argv[optind:])

if files == []:
	files += [sys.stdin]

for file in files:
	for record in map(lambda line: re.split(r' +', line.rstrip()), file):
		print(" ".join(map(format_value, evaluate(script, record))))
