#!/usr/bin/env python
#coding: utf-8
#
# selr フィールドの完全一致を見る（Open usp Tukubai版）
# 
# designed by Nobuaki Tounaka
#
# The MIT License
#
# Copyright (C) 2011 Universal Shell Programming Laboratory
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from __future__ import print_function
import sys

_usage = "selr <field> <str> <file>"
_option = "--through <str>"
_version = "Fri Oct 21 11:26:06 JST 2011"
_code = "Open usp Tukubai (LINUX+FREEBSD/PYTHON2.4/UTF-8)"

def error(msg, *arg):
	print('Error[selr] :', msg % arg, file=sys.stderr)
	sys.exit(1)

def usage():
	print("Usage   :", _usage, file=sys.stderr)
	print("Option  :", _option, file=sys.stderr)
	print("Version :", _version, file=sys.stderr)
	print("         ", _code, file=sys.stderr)
	sys.exit(1)

#
# 入力ファイルオープン
def open_file(filename, mode = 'r'):

	if filename==None or filename == '-': # ファイル名が'-'または省略なら標準入力とする
		file = sys.stdin
	else:
		try:
			file = open(filename, mode)
		except:
			error("ファイル '%s' をオープンできません。", filename)
	return file

#
# 改行符号（\r\n）の削除関数
def rm_eol(line):

	return line.rstrip('\n').rstrip('\r')

#
# フィールド値判定関数
def trymatch(line,fieldnum,string):

	fields=line.split(' ')
	if fields[fieldnum-1]==string: # 指定フィールドの値が指定値と一致した
		return True
	return False

#
# main

if __name__ == '__main__':

	# コマンドの説明表示
	if len(sys.argv) <= 1 \
	 or sys.argv[1] == '--help' \
	 or sys.argv[1] == '--version':
		usage()

	# パラメータ解析
	filename, throughstring = None, None # default値
	numparam=0
	while len(sys.argv) > 1:
		if sys.argv[1] == "--through": # throughオプション
			del(sys.argv[1]) # popup
			if len(sys.argv)==1:
				error("throughオプションの値がありません")
			throughstring=sys.argv[1]
		else:
			numparam+=1
			if numparam==1:
				fieldstring=sys.argv[1] # fieldパラメラ－タ
			elif numparam==2:
				string=sys.argv[1] # strパラメータ
			else:
				filename=sys.argv[1] # fileパラメータ
		del(sys.argv[1]) # popup

	# パラメータ検査
	if numparam<2:
		error("パラメータの数が足りません")
	if not fieldstring.isdigit():
		error("フィールド指定が数値ではありません")
	fieldnum=int(fieldstring)

	# ファイルを開く
	file=open_file(filename)

	# ファイルを読む
	for line in file:
		line=rm_eol(line)
		# throughオプションが無いか、または、throughオプション値とフィールド指定値が一致しないとき
		if not throughstring==string:
			if trymatch(line,fieldnum,string): # 行の指定フィールドの値が指定値と一致したら行を表示
				print(line)
		# throughオプション指定があってフィールド指定値と一致するとき
		else:
			print(line) # 常に行を表示

	# 終了
	sys.exit(0)
