#!/usr/bin/env python
#coding: utf-8
#
# uriencode : URI エンコードを行なう（Open usp Tukubai版）
# 
# designed by Yoshio Katayama
# written  by Hinata Yanagi
#
# The MIT License
#
# Copyright (C) 2023 Universal Shell Programming Laboratory
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from __future__ import print_function

try:
	# Python 2 系
	from urllib import quote
except ImportError:
	# Python 3 系
	from urllib.parse import quote

import sys
import os.path
import select

_command_name = "uriencode"
_usage = _command_name + " [<file>]"
_version = "Tue Mar 21 09:07:51 JST 2023"
_code = "Open usp Tukubai (LINUX+FREEBSD/PYTHON2.4, 3.7/UTF-8)"

def usage():
	print("Usage   :", _usage, file=sys.stderr)
	print("          " + _command_name + " <field> ... <file>")
	print("          " + _command_name + " num=<n> <file>")
	print("          " + _command_name + " -a <file>")
	print("Version :", _version, file=sys.stderr)
	print("         ", _code, file=sys.stderr)
	sys.exit(1)

def escape(string):
	return string.replace('\\\\', '\\').replace('\\n', '\n')

def uriencode(source, num = -1, *field_indices):
	for line in source:
		columns = line.rstrip().split()

		if len(field_indices) == 0:
			if num == -1:
				line = line.replace('\\', '\\\\').replace('\\\\n', '\\n')
				print(quote(line), end = '')
			else:
				head = columns[0:num]
				tail = [quote(escape(' '.join(columns[num:])))]
				print(' '.join(head + tail))
		else:
			for field_index in field_indices:
				columns[field_index] = quote(escape(columns[field_index]))

			print(' '.join(columns))

	source.close()

# main

if __name__ == '__main__':
	# コマンドの説明表示
	if len(sys.argv) == 2 and sys.argv[1] in ['--help', '--version']:
		usage()
	
	if len(sys.argv) == 1:
		uriencode(open('/dev/fd/0'), 0)
	elif len(sys.argv) >= 1 and sys.argv[1].startswith("num="):
		source = open(
			sys.argv[2] if len(sys.argv) == 3 else '/dev/fd/0', 'r')
		uriencode(source, int(sys.argv[1][4:]))
	elif len(sys.argv) >= 1 and sys.argv[1] == "-a":
		source = open(
			sys.argv[2] if len(sys.argv) == 3 else '/dev/fd/0', 'r')
		uriencode(source)
	else:
		source = sys.stdin if \
			select.select([sys.stdin,], [], [], 0)[0] else open(sys.argv[-1], 'r')
		argv = sys.argv[1:] if source == sys.stdin else sys.argv[1:-1]
		uriencode(source, 0, *map(lambda index_str: int(index_str) - 1, argv))

	# 終了
	sys.exit(0)
