#!/usr/bin/env python
#coding: utf-8
# 
# yarr 横アレー: レコードをフィールドへ変換（OpenUSP版）
#
# designed by Nobuaki Tounaka
# written by Ryuichi Ueda
#
# The MIT License
#
# Copyright (C) 2011 Universal Shell Programming Lab.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

_usage = "yarr [num=<n>] [-<m>] <file>"
_version = "Thu Dec  8 11:42:19 JST 2011"
_code = "OpenUSP (LINUX/PYTHON2.4+/UTF-8)"

import re
import os
import sys

class Operator:
	#コンストラクタ
	def __init__(self):
		self.key_num = 0
		self.return_num = None
		self.hold_values = []
		self.hold_keys = []
		self.value_delimiter = ' '

	def setKeyNum(self,num):
		self.key_num = int(num)
		if self.key_num < 0:
			die("キー範囲指定に誤りがあります。")

	def setReturnNum(self,num):
		self.return_num = int(num)
		if self.return_num <= 0:
			die("数字指定に誤りがあります。")

	def setValueDelimiter(self,str):
		self.value_delimiter = str.decode('utf8')

	def output(self,tokens):
		keys = tokens[0:self.key_num]
		values = tokens[self.key_num:]

		if arrayEqual(self.hold_keys,keys):
			self.hold_values += values
		else:
			self.flush()
			self.hold_keys = keys
			self.hold_values = values
			
	def flush(self):
		if len(self.hold_values) == 0: return

		if self.return_num == None:
			keystr = " ".join(self.hold_keys)
			valstr = self.value_delimiter.join(self.hold_values)

			outstr = " ".join([keystr,valstr])
			print outstr.encode('utf_8')
			return
		
		n = 0
		while n < len(self.hold_values):
			m = n + self.return_num
			#指定列数を超えた場合は打ち切る
			if m >= len(self.hold_values): m = len(self.hold_values)

			if len(self.hold_keys) != 0:
				tmp = self.value_delimiter.join(self.hold_values[n:m])
				outstr = self.hold_keys + [tmp];
			else:
				outstr = self.hold_values[n:m]

			print " ".join(outstr).encode('utf_8')

			n += self.return_num

		
	def debugPrint(self):
		print self.key_num, self.return_num

def die(message):
	print >> sys.stderr, "Error[yarr] :", message
	sys.exit(1)

def printUsage():
	print >> sys.stderr , "Usage    :", _usage
	print >> sys.stderr , "Version  :", _version
	print >> sys.stderr , "	  ", _code
	sys.exit(1)

def arrayEqual(array1,array2):
	if len(array1) != len(array2):	return False

	for i in range(len(array1)):
		if array1[i] != array2[i]:
			return False

	return True

def prefixEqual(prefix,token):
	if len(prefix) > len(token):	return False
	
	p = token[0:len(prefix)]
	if p == prefix:	return True

	return False

###########################################
#メイン関数
###########################################
if __name__ == '__main__':

	###########################################
	#ヘルプ
	###########################################
	if len(sys.argv) > 1 \
	 and (sys.argv[1] == '--help' or sys.argv[1] == '--version'):
		printUsage()

	###########################################
	#オプションの処理
	###########################################
	op = Operator()

	file = sys.stdin

	argc = len(sys.argv)
	#ファイルか、num=か、-nか
	for i in range(1, argc):
		arg = sys.argv[i]
		if prefixEqual("-d",arg):	op.setValueDelimiter(arg[2:])
		elif arg == "-":		pass
		elif prefixEqual("-",arg):	op.setReturnNum(arg[1:])
		elif prefixEqual("num=",arg):	op.setKeyNum(arg[4:])
		else:				file = open(arg,'r')

	###########################################
	#出力
	###########################################
	for line in file:
		#utf_8からユニコードに変換して改行を取る
		line = unicode(line, "utf_8").rstrip()
		tokens = line.split(' ')
		op.output(tokens)

	op.flush()
