#!/usr/bin/env python
#coding: utf-8
#
# ysum 横サム（Open usp Tukubai版）
# 
# designed by Nobuaki Tounaka
# written by  Masatomo Togashi
#
# The MIT License
#
# Copyright (C) 2023 Universal Shell Programming Laboratory
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from __future__ import print_function

_usage = "ysum [+h] [num=<n>] <file>"
_version = "Fri May 20 00:00:00 JST 2023"
_code = "Open usp Tukubai (LINUX+FREEBSD/PYTHON2.4/UTF-8)"
_keypatNF=r'(?P<m0>(?P<m01>\d+)|(?P<m02>NF(?P<m03>-\d+)?))$'

import re
import os
import sys
from decimal import Decimal

def error(msg, *arg):
	print('Error[ysum] :', msg % arg, file=sys.stderr)
	sys.exit(1)

def usage():
	print("Usage   :", _usage, file=sys.stderr)
	print("Version :", _version, file=sys.stderr)
	print("         ", _code, file=sys.stderr)
	sys.exit(1)

#
# 入力ファイルオープン
#
def open_file(n):
	if n >= len(sys.argv):	filename = '-'
	else:
		filename = sys.argv[n]
		del sys.argv[n]
	if filename == '-':	filename = '/dev/fd/0'	# sys.stdinをファイルディスクリプターで表記する
	if Python3():	mode='r'
	else:	mode='rU'	# Python2ではmodeがrUのときPython3と同様に読み込み時に各種改行記号がLF（\n）に統一される
	try:
		file = open(filename, mode)
	except:
		if filename=='/dev/fd/0':
			error("標準入力ファイルをオープンできません。")
		else:
			error("ファイル '%s' をオープンできません。", filename)
	return file

# キーフィールド指定処理関連

# NF相対欄位置からNF（欄数）に応じた0発進の欄位置に変換する
def getpos(base_pos):
	# NF相対欄位置からの変換:
	#  nのときはそのまま
	#  0のときはNF（欄数）
	#  -nのときはNF-n
	# 0発進とするために-1を加える
	if base_pos > 0:
		pos=base_pos-1
		if pos >= NF:	error("フィールド番号が大きすぎます。 %s",str(base_pos))
		return pos	# 元からの絶対欄位置
	else:
		pos=NF+base_pos-1
		if pos < 0:	error("フィールド指定でNF-x の x が大きすぎます。 %s","NF-"+str(-base_pos))
		return pos	# NF相対欄位置からの絶対化欄位置

# 欄番号文字列をNF相対形式で整数化する
def getFieldNum(str,str1,str2):
	# n または NF または NF-x の形式の欄番号をNF相対形式の整数で確定する
	# 正規表現で「\d+|NF(-\d+)?」にmatchする全体をstrが、「\d+」でmatchする部分をstr1が、「(-\d+)?」でmatchする部分をstr2が保持している
	# NF相対形式の整数化:
	#  単独のnが0のときはNone
	#  単独のnが0以外のときは整数のn
	#  単独のNFのときは整数の0
	#  NF-nのときは整数の-n
	# 実際の欄番号にする際には行ごとに得たNF（欄数）を使用して計算する
	if str1:	# n
		fieldnum=int(str1)
		if fieldnum==0:	# 欄番号0は全欄を集計対象とすることを意味する
			fieldnum=None
	else:	# NF-n または NF
		if str2:	# NF-n
			fieldnum=int(str2)
		else:	# NF
			fieldnum=0
	return fieldnum

#
# ひとつの欄指定パラメータからNF相対形式で整数化した欄位置を返す
#
def getFieldList(field_param):
	field_param=field_param.replace("NF-0","NF")	# NF-0はNFと書き替える
	mobj = re.match(_keypatNF,field_param)
	if not mobj:	# フィールド指定の形式が不正
		error("フィールド指定の形式が不正です。 %s",fieldnum)
	NFrelpos=getFieldNum(field_param,mobj.group('m01'),mobj.group('m03'))	# NF相対形式で整数化して返す
	return NFrelpos

#
# 行の欄数検査
#
def check_num_fields_variation(fields,keypos):
	global	NF
	start=False
	nf=len(fields)
	if NF==-1:	start=True
	if nf != NF:	# 先頭行かまたは欄数が変化したなら
		NF=nf	# NFを更新
		if start:	start=False	# 先頭行のとき
		else:	# 欄数が変化したとき
			if rel_key>0:	# 絶対欄位置指定なら
				error("numが絶対欄位置指定のときに欄数が変化しました。")
		if rel_key==None:	# 実行時パラメータでnum=0またはnum省略のとき
			keypos=-1	# 全欄を集計対象とするために絶対欄位置を-1に設定する
		else:
			keypos=getpos(rel_key)	# 行の欄数NFを見てNF相対欄位置から絶対欄位置を決定する
	return keypos

# 不要な空白の削除関数
def rm_sp(line):
	return re.sub(r' {2,}',' ',re.sub(r'^ +| +$','',line))	# 行頭と行末の空白を削除し連続空白を単空白にする

# 改行符号（\r\n）の削除関数
def rm_eol(line):
	return line.rstrip("\r\n")	# 改行記号としてCRLF('\r\n')/CR('\r')/LF('\n')のすべてに対応する

# BOMの取得関数
def get_BOM():
	if Python3():	return chr(int("FEFF",16))	# U+FEFFはBOMのUnicode符号位置
	else:			return "\xEF\xBB\xBF"	# BOMは「EF BB BF」の3バイト

# BOMの削除関数
def rm_BOM(line):
	global firstline
	if not firstline: return line
	firstline=False
	if line.startswith(get_BOM()):	line=line[len(get_BOM()):]	# 行頭にBOMがあったらBOMを削除する
	return line

# ファイル入力行の前処理
def preproc_line(line):
	line=rm_eol(line)	# 行末の改行記号を削除する
	line=rm_BOM(line)	# ファイル先頭行の行頭にBOMがあったらこれを削除する
	line=rm_sp(line)	# 行頭と行末の空白を削除し連続空白を単空白にする
	return line

# Python3か判定する
def Python3():
	if sys.version_info >= (3, 0):
		return True
	else:
		return False

#
# フィールド値の取得
#
def getval(line, n):
	if re.match(r'(\+|-)?(\d+\.?|\d*\.\d+)$', line.getField(n)):
		return Decimal(line.getField(n))
	else:
		error("数値変換できません。")

#
# メイン関数
#
if __name__ == '__main__':

	# 構文表示
	if len(sys.argv) < 2: usage()
	elif len(sys.argv) == 2:
		if sys.argv[1] == '--help' or \
		   sys.argv[1] == '--version':	usage()

	#
	# +h
	#
	if len(sys.argv) > 1 and sys.argv[1] == '+h':
		header = True
		del sys.argv[1]
	else:
		header = False

	#
	# num=<n>
	#
	if len(sys.argv) > 1 and sys.argv[1][0:4] == 'num=':
		n=sys.argv[1][4:]
		rel_key = getFieldList(n)	# num=0のときは相対欄位置としてNoneを与える
		del sys.argv[1]
	else:
		rel_key = None	# "num="がないときはnum=0としたときの相対欄位置としてNoneを与える

	file = open_file(1)

	#
	# ヘッダー行
	#
	firstline=True
	if header:
		line = file.readline()
		if not line:
			sys.exit(0)
		print(preproc_line(line), '@')

	#
	# メインループ
	#
	NF=-1
	keypos=-1	# 仮の値で初期設定する
	firstline=True
	for line in file:
		line=preproc_line(line)	# 入力行の前処理
		if not line:	sys.exit(0)
		fields=line.split(" ")
		# 先頭行または欄数変化のあるときはkey指定の検査をする ここで絶対欄位置のkeyposを得る
		keypos=check_num_fields_variation(fields,keypos)
		sum = 0
		for i in range(keypos + 1, len(fields)):
			try:
				sum += Decimal(fields[i])
			except:
				error("数値に変換できません。文字列=%s",fields[i])
		print(line, sum)

	sys.exit(0)
