#!/usr/local/bin/bash -xv
#
# test script of self 
#
# usage: ./self.test <python ver>

tmp=/tmp/$$
+ tmp=/tmp/81120

dir=$(dirname $0)/..
dirname $0)/..
dirname $0
++ dirname ./self.test
+ dir=./..
cd $dir
+ cd ./..

scr=./WORK/self.new
+ scr=./WORK/self.new
com="$1 ${scr}"
+ com=' ./WORK/self.new'
[ "$1" = "" ] && com="./WORK/self.new"
+ '[' '' = '' ']'
+ com=./WORK/self.new

ERROR_CHECK(){
	[ "$(echo ${PIPESTATUS[@]} | tr -d ' 0')" = "" ] && return

	echo $1
	echo "$com" NG
	rm -f $tmp-*
	exit 1
}

###########################################
#TEST1: no option use

cat << FIN > $tmp-in
0000000 浜地______ 50 F 91 59 20 76 54
0000001 鈴田______ 50 F 46 39 8  5  21
0000003 杉山______ 26 F 30 50 71 36 30
0000004 白土______ 40 M 58 71 20 10 6
0000005 崎村______ 50 F 82 79 16 21 80
FIN
+ cat

<< FIN > $tmp-out
浜地______ F
鈴田______ F
杉山______ F
白土______ M
崎村______ F
FIN

${com} 2 4 $tmp-in > $tmp-ans
+ ./WORK/self.new 2 4 /tmp/81120-in
cat $tmp-ans > ./boke
+ cat /tmp/81120-ans
cat $tmp-out > ./bokeboke
+ cat /tmp/81120-out
diff $tmp-ans $tmp-out
+ diff /tmp/81120-ans /tmp/81120-out
[ $? -eq 0 ] ; ERROR_CHECK "TEST1 error"
+ '[' 1 -eq 0 ']'
+ ERROR_CHECK 'TEST1 error'
echo ${PIPESTATUS[@]} | tr -d ' 0')"
echo ${PIPESTATUS[@]} | tr -d ' 0')
echo ${PIPESTATUS[@]} | tr -d ' 0'
++ echo 1
++ tr -d ' 0'
+ '[' 1 = '' ']'
+ echo TEST1 error
+ echo ./WORK/self.new NG
+ rm -f /tmp/81120-ans /tmp/81120-in /tmp/81120-out
+ exit 1
